create or replace view project_weekly_report (ACNT_RID,
                                              ACTIVITY_CODE,
                                              WP_CODE,
                                              NAME,
                                              WORKER,
                                              PLANNED_START,
                                              PLANNED_FINISH,
                                              PLANNED_WORK_TIME,
                                              ACTUAL_START,
                                              ACTUAL_FINISH,
                                              ACTUAL_WORK_TIME,
                                              COMPLETE_RATE,
                                              STATUS,
                                              REMARK,
                                              IS_START,
                                              IS_FINISH,
                                              ACTIVITY_PLANNED_START,
                                              ACTIVITY_ACTUAL_START,
                                              TYPE,
                                              ACTIVITY_RID)
as
select to_char(ACNT_RID),CODE as ACTIVITY_CODE,
       null as WP_CODE, NAME,
       MANAGER as WORKER,
  	   PLANNED_START,
       PLANNED_FINISH,
       (select to_char(sum(PLAN_WORK_TIME)) from PMS_ACTIVITY_WORKERS WORKER WHERE WORKER.ACTIVITY_RID = ACTIVITY.ACTIVITY_RID and WORKER.ACNT_RID = ACTIVITY.ACNT_RID)as PLANNED_WORK_TIME,
  	   ACTUAL_START,
       ACTUAL_FINISH,
       (select to_char(sum(ACTUAL_WORK_TIME)) from PMS_ACTIVITY_WORKERS WORKER WHERE WORKER.ACTIVITY_RID = ACTIVITY.ACTIVITY_RID and WORKER.ACNT_RID = ACTIVITY.ACNT_RID)as ACTUAL_WORK_TIME,
    	 to_char(COMPLETE_RATE) as COMPLETE_RATE ,
       null as STATUS,
       null as REMARK,
       IS_START,IS_FINISH,
       PLANNED_START as ACTIVITY_PLANNED_START,
       PLANNED_FINISH as ACTIVITY_ACTUAL_START ,
       'A' as TYPE,
       ACTIVITY_RID as ACTIVITY_RID
from PMS_ACTIVITY ACTIVITY
UNION
select WP.PROJECT_ID as ACNT_RID,
       '' as ACTIVITY_CODE,
       WP_CODE as WP_CODE,
       WP_NAME as NAME,
       WP_WORKER as WORKER,
    	 WP.WP_PLAN_START as PLANNED_START,
       WP.WP_PLAN_FIHISH as PLANNED_FINISH,
       to_char(WP.WP_PLAN_WKHR) as PLAN_WORK_TIME,
    	 WP.WP_ACT_START as ACTUAL_START,
       WP.WP_ACT_FINISH as ACTUAL_FINISH, 
       to_char(WP.Wp_Act_Wkhr) as ACTUAL_WORK_TIME,
    	 to_char(WP.WP_CMPLTRATE) as COMPLETE_RATE,
       WP.WP_STATUS as STATUS,
       null as REMARK,
       null as IS_START,
       null as IS_FINISH,
    	 ACTIVITY.PLANNED_START as ACTIVITY_PLANNED_START,
       ACTIVITY.PLANNED_FINISH as ACTIVITY_ACTUAL_START,
       'P' as TYPE,
       ACTIVITY.ACTIVITY_RID as ACTIVITY_RID               
    from PW_WP WP,PMS_ACTIVITY ACTIVITY 
    where WP.Project_Id = ACTIVITY.ACNT_RID and WP.ACTIVITY_ID = ACTIVITY.ACTIVITY_RID
    WITH READ ONLY

