package db.essp.issue;

import java.util.Date;


/**
 * IssueMailTemplate generated by MyEclipse - Hibernate Tools
 */

public class IssueMailTemplate  implements java.io.Serializable {


    // Fields

     private Long rid;
     private String issuetype;
     private String cardtype;
     private String templatename;
     private String templatefilepath;
     private String databeanname;
     private String flag;
     private String rst;
     private Date rut;
     private Date rct;


    // Constructors

    /** default constructor */
    public IssueMailTemplate() {
    }

	/** minimal constructor */
    public IssueMailTemplate(Long rid) {
        this.rid = rid;
    }

    /** full constructor */
    public IssueMailTemplate(Long rid, String issuetype, String cardtype, String templatename, String templatefilepath, String databeanname, String flag, String rst, Date rut, Date rct) {
        this.rid = rid;
        this.issuetype = issuetype;
        this.cardtype = cardtype;
        this.templatename = templatename;
        this.templatefilepath = templatefilepath;
        this.databeanname = databeanname;
        this.flag = flag;
        this.rst = rst;
        this.rut = rut;
        this.rct = rct;
    }


    // Property accessors

    public Long getRid() {
        return this.rid;
    }

    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getIssuetype() {
        return this.issuetype;
    }

    public void setIssuetype(String issuetype) {
        this.issuetype = issuetype;
    }

    public String getCardtype() {
        return this.cardtype;
    }

    public void setCardtype(String cardtype) {
        this.cardtype = cardtype;
    }

    public String getTemplatename() {
        return this.templatename;
    }

    public void setTemplatename(String templatename) {
        this.templatename = templatename;
    }

    public String getTemplatefilepath() {
        return this.templatefilepath;
    }

    public void setTemplatefilepath(String templatefilepath) {
        this.templatefilepath = templatefilepath;
    }

    public String getDatabeanname() {
        return this.databeanname;
    }

    public void setDatabeanname(String databeanname) {
        this.databeanname = databeanname;
    }

    public String getFlag() {
        return this.flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public String getRst() {
        return this.rst;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRut() {
        return this.rut;
    }

    public void setRut(Date rut) {
        this.rut = rut;
    }

    public Date getRct() {
        return this.rct;
    }

    public void setRct(Date rct) {
        this.rct = rct;
    }









}
