package db.essp.issue;

import java.util.Date;


/**
 * IssueMailDefaultTemp generated by MyEclipse - Hibernate Tools
 */

public class IssueMailDefaultTemp  implements java.io.Serializable {


    // Fields

     private Long rid;
     private Long acntRid;
     private String issuetype;
     private String cardtype;
     private Long defaulttemplateid;
     private String rst;
     private Date rct;
     private Date rut;


    // Constructors

    /** default constructor */
    public IssueMailDefaultTemp() {
    }

	/** minimal constructor */
    public IssueMailDefaultTemp(Long rid) {
        this.rid = rid;
    }

    /** full constructor */
    public IssueMailDefaultTemp(Long rid, Long acntRid, String issuetype, String cardtype, Long defaulttemplateid, String rst, Date rct, Date rut) {
        this.rid = rid;
        this.acntRid = acntRid;
        this.issuetype = issuetype;
        this.cardtype = cardtype;
        this.defaulttemplateid = defaulttemplateid;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
    }


    // Property accessors

    public Long getRid() {
        return this.rid;
    }

    public void setRid(Long rid) {
        this.rid = rid;
    }

    public Long getAcntRid() {
        return this.acntRid;
    }

    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }

    public String getIssuetype() {
        return this.issuetype;
    }

    public void setIssuetype(String issuetype) {
        this.issuetype = issuetype;
    }

    public String getCardtype() {
        return this.cardtype;
    }

    public void setCardtype(String cardtype) {
        this.cardtype = cardtype;
    }

    public Long getDefaulttemplateid() {
        return this.defaulttemplateid;
    }

    public void setDefaulttemplateid(Long defaulttemplateid) {
        this.defaulttemplateid = defaulttemplateid;
    }

    public String getRst() {
        return this.rst;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }

    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }

    public void setRut(Date rut) {
        this.rut = rut;
    }









}
