package db.essp.issue;

import java.util.Date;


/**
 * IssueMailDefaultTocc generated by MyEclipse - Hibernate Tools
 */

public class IssueMailDefaultTocc  implements java.io.Serializable {


    // Fields

     private Long rid;
     private Long acntRid;
     private String issuetype;
     private Long templaterid;
     private String mailto;
     private String cc;
     private String rst;
     private Date rct;
     private Date rut;


    // Constructors

    /** default constructor */
    public IssueMailDefaultTocc() {
    }

	/** minimal constructor */
    public IssueMailDefaultTocc(Long rid) {
        this.rid = rid;
    }

    /** full constructor */
    public IssueMailDefaultTocc(Long rid, Long acntRid, String issuetype, Long templaterid, String mailto, String cc, String rst, Date rct, Date rut) {
        this.rid = rid;
        this.acntRid = acntRid;
        this.issuetype = issuetype;
        this.templaterid = templaterid;
        this.mailto = mailto;
        this.cc = cc;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
    }


    // Property accessors

    public Long getRid() {
        return this.rid;
    }

    public void setRid(Long rid) {
        this.rid = rid;
    }

    public Long getAcntRid() {
        return this.acntRid;
    }

    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }

    public String getIssuetype() {
        return this.issuetype;
    }

    public void setIssuetype(String issuetype) {
        this.issuetype = issuetype;
    }

    public Long getTemplaterid() {
        return this.templaterid;
    }

    public void setTemplaterid(Long templaterid) {
        this.templaterid = templaterid;
    }

    public String getMailto() {
        return this.mailto;
    }

    public void setMailto(String mailto) {
        this.mailto = mailto;
    }

    public String getCc() {
        return this.cc;
    }

    public void setCc(String cc) {
        this.cc = cc;
    }

    public String getRst() {
        return this.rst;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }

    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }

    public void setRut(Date rut) {
        this.rut = rut;
    }









}
