package db.essp.hrbase;

import java.util.Date;


/**
 * HrbAttributeGroup generated by MyEclipse - Hibernate Tools
 */

public class HrbAttributeGroup  implements java.io.Serializable {


    // Fields    

     private Long rid;
     private Long attributeRid;
     private String site;
     private String code;
     private String description;
     private String isFormal;
     private String isEnable;
     private String rst;
     private String rcu;
     private Date rct;
     private String ruu;
     private Date rut;


    // Constructors

    /** default constructor */
    public HrbAttributeGroup() {
    }

	/** minimal constructor */
    public HrbAttributeGroup(Long rid, Long attributeRid, String site, String code, String isFormal, String isEnable) {
        this.rid = rid;
        this.attributeRid = attributeRid;
        this.site = site;
        this.code = code;
        this.isFormal = isFormal;
        this.isEnable = isEnable;
    }
    
    /** full constructor */
    public HrbAttributeGroup(Long rid, Long attributeRid, String site, String code, String description, String isFormal, String isEnable, String rst, String rcu, Date rct, String ruu, Date rut) {
        this.rid = rid;
        this.attributeRid = attributeRid;
        this.site = site;
        this.code = code;
        this.description = description;
        this.isFormal = isFormal;
        this.isEnable = isEnable;
        this.rst = rst;
        this.rcu = rcu;
        this.rct = rct;
        this.ruu = ruu;
        this.rut = rut;
    }

   
    // Property accessors

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public Long getAttributeRid() {
        return this.attributeRid;
    }
    
    public void setAttributeRid(Long attributeRid) {
        this.attributeRid = attributeRid;
    }

    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getIsFormal() {
        return this.isFormal;
    }
    
    public void setIsFormal(String isFormal) {
        this.isFormal = isFormal;
    }

    public String getIsEnable() {
        return this.isEnable;
    }
    
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable;
    }

    public String getRst() {
        return this.rst;
    }
    
    public void setRst(String rst) {
        this.rst = rst;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public String getRuu() {
        return this.ruu;
    }
    
    public void setRuu(String ruu) {
        this.ruu = ruu;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }

}