package db.essp.hrbase;

import java.util.Date;

/**
 * HrbAttribute generated by MyEclipse - Hibernate Tools
 */

public class HrbAttribute  implements java.io.Serializable {


    // Fields    

     private Long rid;
     private String code;
     private String description;
     private String isEnable;
     private String rst;
     private String rcu;
     private Date rct;
     private String ruu;
     private Date rut;


    // Constructors

    /** default constructor */
    public HrbAttribute() {
    }

	/** minimal constructor */
    public HrbAttribute(Long rid, String code, String isEnable) {
        this.rid = rid;
        this.code = code;
        this.isEnable = isEnable;
    }
    
    /** full constructor */
    public HrbAttribute(Long rid, String code, String description, String isEnable, String rst, String rcu, Date rct, String ruu, Date rut) {
        this.rid = rid;
        this.code = code;
        this.description = description;
        this.isEnable = isEnable;
        this.rst = rst;
        this.rcu = rcu;
        this.rct = rct;
        this.ruu = ruu;
        this.rut = rut;
    }

   
    // Property accessors

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getIsEnable() {
        return this.isEnable;
    }
    
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable;
    }

    public String getRst() {
        return this.rst;
    }
    
    public void setRst(String rst) {
        this.rst = rst;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public String getRuu() {
        return this.ruu;
    }
    
    public void setRuu(String ruu) {
        this.ruu = ruu;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }

}