package db.essp.hrbase;

import java.util.Date;


/**
 * HrbHumanBaseData generated by MyEclipse - Hibernate Tools
 */

public class HrbHumanBase  implements java.io.Serializable {


    // Fields    

     private Long rid;
     private String employeeId;
     private String unitCode;
     private String englishName;
     private String chineseName;
     private String title;
     private String rank;
     private String resManagerId;
     private String resManagerName;
     private String email;
     private Date inDate;
     private Date outDate;
     private String site;
     private String attribute;
     private Date effectiveDate;
     private String operation;
     private String rst;
     private Date rut;
     private Date rct;
     private String rcu;
     private String ruu;
     private Long attributeGroupRid;
     private String isDirect;


    // Constructors

    public Long getAttributeGroupRid() {
		return attributeGroupRid;
	}

	public void setAttributeGroupRid(Long attributeGroupRid) {
		this.attributeGroupRid = attributeGroupRid;
	}

	public String getIsDirect() {
		return isDirect;
	}

	public void setIsDirect(String isDirect) {
		this.isDirect = isDirect;
	}

	/** default constructor */
    public HrbHumanBase() {
    }

	/** minimal constructor */
    public HrbHumanBase(Long rid, String employeeId) {
        this.rid = rid;
        this.employeeId = employeeId;
    }
    
    /** full constructor */
    public HrbHumanBase(Long rid, String employeeId, String unitCode,
            String englishName, String chineseName, String title, String rank,
            String resManagerId, String resManagerName, String email,
            Date inDate, Date outDate, String site, String rst, Date rut,
            Date rct, String rcu, String ruu,String operation) {
        this.rid = rid;
        this.employeeId = employeeId;
        this.unitCode = unitCode;
        this.englishName = englishName;
        this.chineseName = chineseName;
        this.title = title;
        this.rank = rank;
        this.resManagerId = resManagerId;
        this.resManagerName = resManagerName;
        this.email = email;
        this.inDate = inDate;
        this.outDate = outDate;
        this.site = site;
        this.rst = rst;
        this.rut = rut;
        this.rct = rct;
        this.rcu = rcu;
        this.ruu = ruu;
        this.operation = operation;
    }

   
    // Property accessors

    public long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getChineseName() {
        return this.chineseName;
    }
    
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getRank() {
        return this.rank;
    }
    
    public void setRank(String rank) {
        this.rank = rank;
    }

    public String getResManagerId() {
        return this.resManagerId;
    }
    
    public void setResManagerId(String resManagerId) {
        this.resManagerId = resManagerId;
    }

    public String getResManagerName() {
        return this.resManagerName;
    }
    
    public void setResManagerName(String resManagerName) {
        this.resManagerName = resManagerName;
    }
    public Date getInDate() {
        return this.inDate;
    }
    
    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public String getRuu() {
        return this.ruu;
    }
    
    public void setRuu(String ruu) {
        this.ruu = ruu;
    }

    public Date getEffectiveDate() {
        return effectiveDate;
    }

    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    public String getEnglishName() {
        return englishName;
    }

    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    public Date getOutDate() {
        return outDate;
    }

    public void setOutDate(Date outDate) {
        this.outDate = outDate;
    }

    public String getRst() {
        return rst;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }

    public String getUnitCode() {
        return unitCode;
    }

    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }

    public String getOperation() {
        return operation;
    }

    public void setOperation(String operation) {
        this.operation = operation;
    }

	public String getAttribute() {
		return attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}
	
	public String getCanUpdate() {
		if(this.getOperation() == null) {
			return "false";
		} else if(HrbHumanBaseLog.OPERATION_NONE.equals(this.getOperation())) {
			return "true";
		} else {
			return "false";
		}
	}
	
	/**
     * englishName(chineseName)
     * @return
     */
    public String getFullName() {
        return ecName2FullName(this.getEnglishName(), this.getChineseName());
    }
    
    public static String ecName2FullName(final String eName, final String cName) {
        String fullName = eName;
        if(fullName == null) {
            return cName;
        }
        if(cName != null && "".equals(cName) == false) {
            fullName += "(" + cName + ")";
        }
        return fullName;
    }
}