package db.essp.hrbase;

import java.util.Date;


/**
 * HrbUnitBaseData generated by MyEclipse - Hibernate Tools
 */

public class HrbUnitBase  implements java.io.Serializable {


    // Fields    

     private Long rid;
     private String unitCode;
     private String unitName;
     private String unitFullName;
     private String parentUnitCode;
     private String dmId;
     private String dmName;
     private String tsId;
     private String tsName;
     private String bdId;
     private String bdName;
     private String applicantId;
     private String applicantName;
     private String belongBd;
     private Date effectiveDate;
     private Date effectiveBegin;
     private Date effectiveEnd;
     private String operation;
     private String belongSite;
     private String acntAttribute;
     private String costBelongUnit;
     private String isBl;
     private String rst;
     private Date rut;
     private Date rct;
     private String rcu;
     private String ruu;


    // Constructors

    /** default constructor */
    public HrbUnitBase() {
    }

	/** minimal constructor */
    public HrbUnitBase(Long rid) {
        this.rid = rid;
    }
    
    /** full constructor */
    public HrbUnitBase(Long rid, String unitCode, String unitName,String unitFullName,String acntAttribute,
            String parentUnitCode, String bdId, String bdName,String dmId,String dmName,String applicantId,String applicantName,
            String tsId,String tsName,String belongBd, String belongSite, String isBl, String rst, Date rut,
            Date rct, String rcu, String ruu, Date effectiveDate,String operation) {
        this.rid = rid;
        this.unitCode = unitCode;
        this.unitName = unitName;
        this.parentUnitCode = parentUnitCode;
        this.bdId = bdId;
        this.bdName = bdName;
        this.dmId=dmId;
        this.dmName=dmName;
        this.tsId=tsId;
        this.tsName=tsName;
        this.applicantId = applicantId;
        this.applicantName = applicantName;
        this.belongBd = belongBd;
        this.operation = operation;
        this.effectiveDate = effectiveDate;
        this.belongSite = belongSite;
        this.unitFullName = unitFullName;
        this.acntAttribute = acntAttribute;
        this.isBl = isBl;
        this.rst = rst;
        this.rut = rut;
        this.rct = rct;
        this.rcu = rcu;
        this.ruu = ruu;
    }

   
    // Property accessors

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getUnitCode() {
        return this.unitCode;
    }
    
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }

    public String getUnitName() {
        return this.unitName;
    }
    
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    public String getParentUnitCode() {
        return this.parentUnitCode;
    }
    
    public void setParentUnitCode(String parentUnitCode) {
        this.parentUnitCode = parentUnitCode;
    }

    public String getBelongBd() {
        return belongBd;
    }

    public void setBelongBd(String belongBd) {
        this.belongBd = belongBd;
    }

    public String getAcntAttribute() {
        return acntAttribute;
    }

    public void setAcntAttribute(String acntAttribute) {
        this.acntAttribute = acntAttribute;
    }

    public String getBdId() {
        return bdId;
    }

    public void setBdId(String bdId) {
        this.bdId = bdId;
    }

    public String getBdName() {
        return bdName;
    }

    public void setBdName(String bdName) {
        this.bdName = bdName;
    }

    public String getBelongSite() {
        return belongSite;
    }

    public void setBelongSite(String belongSite) {
        this.belongSite = belongSite;
    }

    public String getDmId() {
        return dmId;
    }

    public void setDmId(String dmId) {
        this.dmId = dmId;
    }

    public String getDmName() {
        return dmName;
    }

    public void setDmName(String dmName) {
        this.dmName = dmName;
    }

    public String getTsId() {
        return tsId;
    }

    public void setTsId(String tsId) {
        this.tsId = tsId;
    }

    public String getTsName() {
        return tsName;
    }

    public void setTsName(String tsName) {
        this.tsName = tsName;
    }

    public String getUnitFullName() {
        return unitFullName;
    }

    public void setUnitFullName(String unitFullName) {
        this.unitFullName = unitFullName;
    }

    public String getRst() {
        return this.rst;
    }
    
    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public String getRuu() {
        return this.ruu;
    }
    
    public void setRuu(String ruu) {
        this.ruu = ruu;
    }

    public Date getEffectiveDate() {
        return effectiveDate;
    }

    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    public String getOperation() {
        return operation;
    }

    public void setOperation(String operation) {
        this.operation = operation;
    }

    public String getApplicantId() {
        return applicantId;
    }

    public void setApplicantId(String applicantId) {
        this.applicantId = applicantId;
    }

    public String getApplicantName() {
        return applicantName;
    }

    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName;
    }


    public String getCostBelongUnit() {
        return costBelongUnit;
    }

    public void setCostBelongUnit(String costBelongUnit) {
        this.costBelongUnit = costBelongUnit;
    }

    public Date getEffectiveEnd() {
        return effectiveEnd;
    }

    public void setEffectiveEnd(Date effectiveEnd) {
        this.effectiveEnd = effectiveEnd;
    }

    public Date getEffectiveBegin() {
        return effectiveBegin;
    }

    public void setEffectiveBegin(Date effectiveBegin) {
        this.effectiveBegin = effectiveBegin;
    }

	public String getIsBl() {
		return isBl;
	}

	public void setIsBl(String isBl) {
		this.isBl = isBl;
	}
   
}