package db.essp.tc;

import java.math.BigDecimal;
import java.util.Date;


/**
 * TcProcess generated by MyEclipse - Hibernate Tools
 */

public class TcProcess  implements java.io.Serializable {


    // Fields

     private Long rid;
     private String loginId;
     private String tcType;
     private String processType;
     private BigDecimal processHours;
     private Long yearth;
     private BigDecimal subOvertimeHours;
     private BigDecimal subAnnualHours;
     private Date rut;
     private String status;
     private String remark;


    // Constructors

    /** default constructor */
    public TcProcess() {
    }

	/** minimal constructor */
    public TcProcess(Long rid, String loginId, String tcType, String processType, BigDecimal processHours) {
        this.rid = rid;
        this.loginId = loginId;
        this.tcType = tcType;
        this.processType = processType;
        this.processHours = processHours;
    }



    // Property accessors

    public Long getRid() {
        return this.rid;
    }

    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getLoginId() {
        return this.loginId;
    }

    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    public String getTcType() {
        return this.tcType;
    }

    public void setTcType(String tcType) {
        this.tcType = tcType;
    }

    public String getProcessType() {
        return this.processType;
    }

    public void setProcessType(String processType) {
        this.processType = processType;
    }

    public BigDecimal getProcessHours() {
        return this.processHours;
    }

    public void setProcessHours(BigDecimal processHours) {
        this.processHours = processHours;
    }

    public Long getYearth() {

        return yearth;
    }

    public void setYearth(Long yearth) {

        this.yearth = yearth;
    }

    public BigDecimal getSubOvertimeHours() {

        return subOvertimeHours;
    }

    public void setSubOvertimeHours(BigDecimal subOvertimeHours) {

        this.subOvertimeHours = subOvertimeHours;
    }

    public BigDecimal getSubAnnualHours() {

        return subAnnualHours;
    }

    public void setSubAnnualHours(BigDecimal subAnnualHours) {

        this.subAnnualHours = subAnnualHours;
    }

    public Date getRut() {
        return this.rut;
    }

    public void setRut(Date rut) {
        this.rut = rut;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }









}
