package server.essp.projectpre.db;

import java.util.Date;


/**
 * PpAcntCustContactor generated by MyEclipse - Hibernate Tools
 */

public class AcntCustContactor  implements java.io.Serializable {


    // Fields    

     private Long rid;
     private Long acntRid;
     private String contactorType;
     private String telephone;
     private String email;
     private String name;
     private String description;
     private String rst;
     private Date rct;
     private Date rut;
     private String rcu;
     private String ruu;


    // Constructors

    /** default constructor */
    public AcntCustContactor() {
    }

	/** minimal constructor */
    public AcntCustContactor(Long rid) {
        this.rid = rid;
    }
    
    /** full constructor */
    public AcntCustContactor(Long rid, Long acntRid, String contactorType, String telephone, String email, String name, String description, String rst, Date rct, Date rut, String rcu, String ruu) {
        this.rid = rid;
        this.acntRid = acntRid;
        this.contactorType = contactorType;
        this.telephone = telephone;
        this.email = email;
        this.name = name;
        this.description = description;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
        this.rcu = rcu;
        this.ruu = ruu;
    }

   
    // Property accessors

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public Long getAcntRid() {
        return this.acntRid;
    }
    
    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }

    public String getContactorType() {
        return this.contactorType;
    }
    
    public void setContactorType(String contactorType) {
        this.contactorType = contactorType;
    }

    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getRst() {
        return this.rst;
    }
    
    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public String getRuu() {
        return this.ruu;
    }
    
    public void setRuu(String ruu) {
        this.ruu = ruu;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
   








}