package server.essp.projectpre.db;

import java.util.Date;


/**
 * PpAcntTechinfoApp generated by MyEclipse - Hibernate Tools
 */

public class AcntTechinfoApp  implements java.io.Serializable {


    // Fields    

     private AcntTechinfoAppId id=new AcntTechinfoAppId();
     private Long rid;
     private String description;
     private String rst;
     private Date rct;
     private Date rut;
     private String rcu;
     private String ruu;


    // Constructors

    /** default constructor */
    public AcntTechinfoApp() {
    }

	/** minimal constructor */
    public AcntTechinfoApp(AcntTechinfoAppId id, Long rid) {
        this.id = id;
        this.rid = rid;
    }
    
    /** full constructor */
    public AcntTechinfoApp(AcntTechinfoAppId id, Long rid, String description, String rst, Date rct, Date rut, String rcu, String ruu) {
        this.id = id;
        this.rid = rid;
        this.description = description;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
        this.rcu = rcu;
        this.ruu = ruu;
    }

   
    // Property accessors

    public AcntTechinfoAppId getId() {
        return this.id;
    }
    
    public void setId(AcntTechinfoAppId id) {
        this.id = id;
    }

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getRst() {
        return this.rst;
    }
    
    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public String getRuu() {
        return this.ruu;
    }
    
    public void setRuu(String ruu) {
        this.ruu = ruu;
    }
   








}