package server.essp.projectpre.db;

import java.util.Date;


/**
 * PpAcntPerson generated by MyEclipse - Hibernate Tools
 */

public class AcntPerson  implements java.io.Serializable {


    // Fields    

     private Long rid;
     private Long acntRid;
     private String personType;
     private String domain;
     private String loginId;
     private String name;
     private String rst;
     private Date rct;
     private Date rut;
     private String rcu;
     private String ruu;


    // Constructors

    /** default constructor */
    public AcntPerson() {
    }

	/** minimal constructor */
    public AcntPerson(Long rid) {
        this.rid = rid;
    }
    
    /** full constructor */
    public AcntPerson(Long rid, Long acntRid, String personType,String domain, String loginId, String name, String rst, Date rct, Date rut, String rcu, String ruu) {
        this.rid = rid;
        this.acntRid = acntRid;
        this.personType = personType;
        this.domain = domain;
        this.loginId = loginId;
        this.name = name;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
        this.rcu = rcu;
        this.ruu = ruu;
    }

   
    // Property accessors

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public Long getAcntRid() {
        return this.acntRid;
    }
    
    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }

    public String getPersonType() {
        return this.personType;
    }
    
    public void setPersonType(String personType) {
        this.personType = personType;
    }

    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getRst() {
        return this.rst;
    }
    
    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public String getRuu() {
        return this.ruu;
    }
    
    public void setRuu(String ruu) {
        this.ruu = ruu;
    }

	public String getDomain() {
		return domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}
   








}