package server.essp.projectpre.db;



/**
 * PpAcntQueryPrivilegeId generated by MyEclipse - Hibernate Tools
 */

public class AcntQueryPrivilege  implements java.io.Serializable {


    // Fields    

     private String loginId;
     private Long acntRid;
     private String orgPrivilege;
     private String vcodePrivilege;


    // Constructors

    /** default constructor */
    public AcntQueryPrivilege() {
    }

	/** minimal constructor */
    public AcntQueryPrivilege(String loginId, Long acntRid) {
        this.loginId = loginId;
        this.acntRid = acntRid;
    }
    
    /** full constructor */
    public AcntQueryPrivilege(String loginId, Long acntRid, String orgPrivilege, String vcodePrivilege) {
        this.loginId = loginId;
        this.acntRid = acntRid;
        this.orgPrivilege = orgPrivilege;
        this.vcodePrivilege = vcodePrivilege;
    }

   
    // Property accessors

    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    public Long getAcntRid() {
        return this.acntRid;
    }
    
    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }

    public String getOrgPrivilege() {
        return this.orgPrivilege;
    }
    
    public void setOrgPrivilege(String orgPrivilege) {
        this.orgPrivilege = orgPrivilege;
    }

	public String getVcodePrivilege() {
		return vcodePrivilege;
	}

	public void setVcodePrivilege(String vcodePrivilege) {
		this.vcodePrivilege = vcodePrivilege;
	}
   
}
