package server.essp.projectpre.db;

import java.util.Date;


/**
 * PpAcntCustContactorApp generated by MyEclipse - Hibernate Tools
 */

public class AcntCustContactorApp  implements java.io.Serializable {


    // Fields    

     private Long rid;
     private Long acntAppRid;
     private String contactorType;
     private String telephone;
     private String email;
     private String name;
     private String description;
     private String rst;
     private Date rct;
     private Date rut;
     private String rcu;
     private Date ruu;


    // Constructors

    /** default constructor */
    public AcntCustContactorApp() {
    }

	/** minimal constructor */
    public AcntCustContactorApp(Long rid) {
        this.rid = rid;
    }
    
    /** full constructor */
    public AcntCustContactorApp(Long rid, Long acntAppRid, String contactorType, String telephone, String email, String name,String description, String rst, Date rct, Date rut, String rcu, Date ruu) {
        this.rid = rid;
        this.acntAppRid = acntAppRid;
        this.contactorType = contactorType;
        this.telephone = telephone;
        this.email = email;
        this.name = name;
        this.description = description;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
        this.rcu = rcu;
        this.ruu = ruu;
    }

   
    // Property accessors

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public Long getAcntAppRid() {
        return this.acntAppRid;
    }
    
    public void setAcntAppRid(Long acntAppRid) {
        this.acntAppRid = acntAppRid;
    }

    public String getContactorType() {
        return this.contactorType;
    }
    
    public void setContactorType(String contactorType) {
        this.contactorType = contactorType;
    }

    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getRst() {
        return this.rst;
    }
    
    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public Date getRuu() {
        return this.ruu;
    }
    
    public void setRuu(Date ruu) {
        this.ruu = ruu;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
   








}