package server.essp.projectpre.db;

import java.util.Date;


/**
 * PpBd generated by MyEclipse - Hibernate Tools
 */

public class Bd  implements java.io.Serializable {


    // Fields    

     private String bdCode;
     private Long rid;
     private String bdName;
     private String description;
     private Long sequence;
     private boolean status;
     private boolean achieveBelong;
     private String rst;
     private Date rct;
     private Date rut;
     private String rcu;
     private String ruu;


    // Constructors

    /** default constructor */
    public Bd() {
    }

	/** minimal constructor */
    public Bd(String bdCode, Long rid) {
        this.bdCode = bdCode;
        this.rid = rid;
    }
    
    /** full constructor */
    public Bd(String bdCode, Long rid, String bdName, String description, Long sequence,boolean status,boolean achieveBelong, String rst, Date rct, Date rut, String rcu, String ruu) {
        this.bdCode = bdCode;
        this.rid = rid;
        this.bdName = bdName;
        this.description = description;
        this.sequence = sequence;
        this.status = status;
        this.achieveBelong = achieveBelong;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
        this.rcu = rcu;
        this.ruu = ruu;
    }

   
    // Property accessors

    public String getBdCode() {
        return this.bdCode;
    }
    
    public void setBdCode(String bdCode) {
        this.bdCode = bdCode;
    }

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getBdName() {
        return this.bdName;
    }
    
    public void setBdName(String bdName) {
        this.bdName = bdName;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Long getSequence() {
        return this.sequence;
    }
    
    public void setSequence(Long sequence) {
        this.sequence = sequence;
    }

    public String getRst() {
        return this.rst;
    }
    
    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public String getRuu() {
        return this.ruu;
    }
    
    public void setRuu(String ruu) {
        this.ruu = ruu;
    }

	public boolean getStatus() {
		return status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

    public boolean getAchieveBelong() {
        return achieveBelong;
    }

    public void setAchieveBelong(boolean achieveBelong) {
        this.achieveBelong = achieveBelong;
    }
   








}