package server.essp.projectpre.db;

import java.util.Date;


/**
 * PcCustomerApplication generated by MyEclipse - Hibernate Tools
 */

public class CustomerApplication  implements java.io.Serializable {


    // Fields    

     private Long rid;
     private String applicationType;
     private String applicationStatus;
     private String applicantId;
     private String applicantName;
     private Date applicationDate;
     private String attribute;
     private String customerRid;
     private String customerId;
     private String regId;
     private String groupId;
     private String customerShort;
     private String customerNameCn;
     private String customerNameEn;
     private String belongBd;
     private String belongSite;
     private String customerClass;
     private String customerCountry;
     private String custDescription;
     private String description;
     private String rst;
     private Date rct;
     private Date rut;
     private String rcu;
     private String ruu;


    // Constructors

    /** default constructor */
    public CustomerApplication() {
    }

	/** minimal constructor */
    public CustomerApplication(Long rid) {
        this.rid = rid;
    }
    
    /** full constructor */
    public CustomerApplication(Long rid, String applicationType, String applicationStatus, String applicantId,String applicantName, Date applicationDate,  String attribute, String customerRid,String customerId, String regId, String groupId, String customerShort, String customerNameCn, String customerNameEn, String belongBd, String belongSite, String customerClass, String customerCountry,String custDescription, String description, String rst, Date rct, Date rut, String rcu, String ruu) {
        this.rid = rid;
        this.applicationType = applicationType;
        this.applicationStatus = applicationStatus;
        this.applicantId = applicantId;
        this.applicantName = applicantName;
        this.applicationDate = applicationDate;
 
        this.attribute = attribute;
        this.customerRid = customerRid;
        this.customerId = customerId;
        this.regId = regId;
        this.groupId = groupId;
        this.customerShort = customerShort;
        this.customerNameCn = customerNameCn;
        this.customerNameEn = customerNameEn;
        this.belongBd = belongBd;
        this.belongSite = belongSite;
        this.customerClass = customerClass;
        this.customerCountry = customerCountry;
        this.custDescription=custDescription;
        this.description = description;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
        this.rcu = rcu;
        this.ruu = ruu;
    }

   
    // Property accessors

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getApplicationType() {
        return this.applicationType;
    }
    
    public void setApplicationType(String applicationType) {
        this.applicationType = applicationType;
    }

    public String getApplicationStatus() {
        return this.applicationStatus;
    }
    
    public void setApplicationStatus(String applicationStatus) {
        this.applicationStatus = applicationStatus;
    }

    public Date getApplicationDate() {
        return this.applicationDate;
    }
    
    public void setApplicationDate(Date applicationDate) {
        this.applicationDate = applicationDate;
    }

    public String getAttribute() {
        return this.attribute;
    }
    
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    public String getCustomerRid() {
        return this.customerRid;
    }
    
    public void setCustomerRid(String customerRid) {
        this.customerRid = customerRid;
    }

    public String getRegId() {
        return this.regId;
    }
    
    public void setRegId(String regId) {
        this.regId = regId;
    }

    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getCustomerShort() {
        return this.customerShort;
    }
    
    public void setCustomerShort(String customerShort) {
        this.customerShort = customerShort;
    }

    public String getCustomerNameCn() {
        return this.customerNameCn;
    }
    
    public void setCustomerNameCn(String customerNameCn) {
        this.customerNameCn = customerNameCn;
    }

    public String getCustomerNameEn() {
        return this.customerNameEn;
    }
    
    public void setCustomerNameEn(String customerNameEn) {
        this.customerNameEn = customerNameEn;
    }

    public String getBelongBd() {
        return this.belongBd;
    }
    
    public void setBelongBd(String belongBd) {
        this.belongBd = belongBd;
    }

    public String getBelongSite() {
        return this.belongSite;
    }
    
    public void setBelongSite(String belongSite) {
        this.belongSite = belongSite;
    }

    public String getCustomerClass() {
        return this.customerClass;
    }
    
    public void setCustomerClass(String customerClass) {
        this.customerClass = customerClass;
    }

    public String getCustomerCountry() {
        return this.customerCountry;
    }
    
    public void setCustomerCountry(String customerCountry) {
        this.customerCountry = customerCountry;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getRst() {
        return this.rst;
    }
    
    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public String getRuu() {
        return this.ruu;
    }
    
    public void setRuu(String ruu) {
        this.ruu = ruu;
    }


    public String getCustDescription() {
		return custDescription;
	}

	public void setCustDescription(String custDescription) {
		this.custDescription = custDescription;
	}

    public String getApplicantId() {
        return applicantId;
    }

    public void setApplicantId(String applicantId) {
        this.applicantId = applicantId;
    }

    public String getApplicantName() {
        return applicantName;
    }

    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

  
   








}