package server.essp.projectpre.db;

import java.util.Date;


/**
 * PpIdSetting generated by MyEclipse - Hibernate Tools
 */

public class IdSetting  implements java.io.Serializable {


    // Fields    

     private Long rid;
     private String idType;
     private Long length;
     private Long currentSeq;
     private String firstChar;
     private String codingMethod;
     private String codingGenerate;
     private String rst;
     private Date rct;
     private Date rut;
     private String rcu;
     private String ruu;


    // Constructors

    public String getCodingGenerate() {
		return codingGenerate;
	}

	public void setCodingGenerate(String codingGenerate) {
		this.codingGenerate = codingGenerate;
	}

	public String getCodingMethod() {
		return codingMethod;
	}

	public void setCodingMethod(String codingMethod) {
		this.codingMethod = codingMethod;
	}

	/** default constructor */
    public IdSetting() {
    }

	/** minimal constructor */
    public IdSetting(Long rid) {
        this.rid = rid;
    }
    
    /** full constructor */
    public IdSetting(Long rid, String idType, Long length, Long currentSeq, String firstChar,String codingMethod,String codingGenerate, String rst, Date rct, Date rut, String rcu, String ruu) {
        this.rid = rid;
        this.idType = idType;
        this.length = length;
        this.currentSeq = currentSeq;
        this.firstChar = firstChar;
        this.codingMethod = codingMethod;
        this.codingGenerate = codingGenerate;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
        this.rcu = rcu;
        this.ruu = ruu;
    }

   
    // Property accessors

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getIdType() {
        return this.idType;
    }
    
    public void setIdType(String idType) {
        this.idType = idType;
    }

    public Long getLength() {
        return this.length;
    }
    
    public void setLength(Long length) {
        this.length = length;
    }

    public Long getCurrentSeq() {
        return this.currentSeq;
    }
    
    public void setCurrentSeq(Long currentSeq) {
        this.currentSeq = currentSeq;
    }

    public String getFirstChar() {
        return this.firstChar;
    }
    
    public void setFirstChar(String firstChar) {
        this.firstChar = firstChar;
    }

    public String getRst() {
        return this.rst;
    }
    
    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public String getRuu() {
        return this.ruu;
    }
    
    public void setRuu(String ruu) {
        this.ruu = ruu;
    }
   








}