package server.essp.projectpre.db;

import java.util.Date;


/**
 * PpLastRud generated by MyEclipse - Hibernate Tools
 */

public class LastRud  implements java.io.Serializable {


    // Fields    

     private LastRudId id=new LastRudId();
     private Long rid;
     private Date lastRud;
     private String rst;
     private Date rct;
     private Date rut;


    // Constructors

    /** default constructor */
    public LastRud() {
    }

	/** minimal constructor */
    public LastRud(LastRudId id) {
        this.id = id;
    }
    
    /** full constructor */
    public LastRud(LastRudId id, Long rid, Date lastRud, String rst, Date rct, Date rut) {
        this.id = id;
        this.rid = rid;
        this.lastRud = lastRud;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
    }

   
    // Property accessors

    public LastRudId getId() {
        return this.id;
    }
    
    public void setId(LastRudId id) {
        this.id = id;
    }

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public Date getLastRud() {
        return this.lastRud;
    }
    
    public void setLastRud(Date lastRud) {
        this.lastRud = lastRud;
    }

    public String getRst() {
        return this.rst;
    }
    
    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }
   








}