package server.essp.projectpre.db;

import java.util.Date;


/**
 * PpParameter generated by MyEclipse - Hibernate Tools
 */

public class Parameter  implements java.io.Serializable {


    // Fields    

     private ParameterId compId = new ParameterId();
     private Long rid;
     private String name;
     private String alias;
     private String description;
     private Long sequence;
     private Boolean status;
     private String rst;
     private Date rct;
     private Date rut;


    // Constructors

    /** default constructor */
    public Parameter() {
    }

	/** minimal constructor */
    public Parameter(ParameterId compId) {
        this.compId = compId;
    }
    
    /** full constructor */
    public Parameter(ParameterId compId, Long rid, String name, String alias, String description, Long sequence,Boolean status, String rst, Date rct, Date rut) {
        this.compId = compId;
        this.rid = rid;
        this.name = name;
        this.alias = alias;
        this.description = description;
        this.sequence = sequence;
        this.status = status;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
    }

   
    // Property accessors

    public ParameterId getCompId() {
        return this.compId;
    }
    
    public void setCompId(ParameterId compId) {
        this.compId = compId;
    }

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Long getSequence() {
        return this.sequence;
    }
    
    public void setSequence(Long sequence) {
        this.sequence = sequence;
    }

    public String getRst() {
        return this.rst;
    }
    
    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }


	public Boolean getStatus() {

		return status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}
   








}