package server.essp.projectpre.db;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * PPLog generated by MyEclipse - Hibernate Tools
 */
public class PPLog implements java.io.Serializable {
    private Long rid;
    private String acntId; //专案代码或申请单号
    private String dataType;//资料类型
    private String applicationType;//申请类型
    private String operation;//操作
    private String operator;//操作者
    private String mailReceiver;//邮件接收者
    private Date operationDate;//操作日期
    
	
    // Constructors

    /** default constructor */
    public PPLog() {
    }

	
    
    /** full constructor */
    public PPLog(Long rid,String acntId, String dataType, String applicationType, String operation, Date operationDate, String operator, String mailReceiver) {
      this.rid=rid;
      this.acntId=acntId;
      this.dataType=dataType;
      this.applicationType=applicationType;
      this.operation=operation;
      this.operationDate=operationDate;
      this.operator=operator;
      this.mailReceiver=mailReceiver;
    }

	public String getAcntId() {
		return acntId;
	}

	public void setAcntId(String acntId) {
		this.acntId = acntId;
	}

	public String getApplicationType() {
		return applicationType;
	}

	public void setApplicationType(String applicationType) {
		this.applicationType = applicationType;
	}

	public String getDataType() {
		return dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	public String getMailReceiver() {
		return mailReceiver;
	}

	public void setMailReceiver(String mailReceiver) {
		this.mailReceiver = mailReceiver;
	}

	public String getOperation() {
		return operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	public Date getOperationDate() {
		return operationDate;
	}

	public void setOperationDate(Date operationDate) {
		this.operationDate = operationDate;
	}

	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public Long getRid() {
	    return this.rid;
	}
	    

	public void setRid(Long rid) {
		this.rid = rid;
	}
   
}
