package server.essp.projectpre.db;

import java.util.Date;


/**
 * PpSyncException generated by MyEclipse - Hibernate Tools
 */

public class PpSyncException  implements java.io.Serializable {


    // Fields    

     private long rid;
     private long acntRid;
     private String acntId;
     private String acntName;
     private String model;
     private String status;
     private String errorMessage;
     private String type;
     private String impClassName;
     private String rcu;
     private String ruu;
     private Date rct;
     private Date rut;


    // Constructors

    /** default constructor */
    public PpSyncException() {
    }

	/** minimal constructor */
    public PpSyncException(long rid, long acntRid) {
        this.rid = rid;
        this.acntRid = acntRid;
    }
    
    /** full constructor */
    public PpSyncException(long rid, long acntRid, String acntId, String acntName, String model, String status, String errorMessage, String type, String impClassName, String rcu, String ruu, Date rct, Date rut) {
        this.rid = rid;
        this.acntRid = acntRid;
        this.acntId = acntId;
        this.acntName = acntName;
        this.model = model;
        this.status = status;
        this.errorMessage = errorMessage;
        this.type = type;
        this.impClassName = impClassName;
        this.rcu = rcu;
        this.ruu = ruu;
        this.rct = rct;
        this.rut = rut;
    }

   
    // Property accessors

    public long getRid() {
        return this.rid;
    }
    
    public void setRid(long rid) {
        this.rid = rid;
    }

    public long getAcntRid() {
        return this.acntRid;
    }
    
    public void setAcntRid(long acntRid) {
        this.acntRid = acntRid;
    }

    public String getAcntId() {
        return this.acntId;
    }
    
    public void setAcntId(String acntId) {
        this.acntId = acntId;
    }

    public String getAcntName() {
        return this.acntName;
    }
    
    public void setAcntName(String acntName) {
        this.acntName = acntName;
    }

    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getErrorMessage() {
        return this.errorMessage;
    }
    
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    public String getImpClassName() {
        return this.impClassName;
    }
    
    public void setImpClassName(String impClassName) {
        this.impClassName = impClassName;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public String getRuu() {
        return this.ruu;
    }
    
    public void setRuu(String ruu) {
        this.ruu = ruu;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }
   








}