package server.essp.projectpre.db;

import java.util.Date;


/**
 * Site generated by MyEclipse - Hibernate Tools
 */

public class Site  implements java.io.Serializable {

    // Fields    

     private Long rid;
     private String siteName;
     private String siteCode;
     private String description;
     private String manager;
     private boolean status;
     private String rst;
     private Date rct;
     private Date rut;
     private String rcu;
     private String ruu;
     private Long siteLoading;


    // Constructors

    public Long getSiteLoading() {
		return siteLoading;
	}

	public void setSiteLoading(Long siteLoading) {
		this.siteLoading = siteLoading;
	}

	/** default constructor */
    public Site() {
    }

	/** minimal constructor */
    public Site(Long rid) {
        this.rid = rid;
    }
    // Property accessors

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getSiteName() {
        return this.siteName;
    }
    
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    public String getSiteCode() {
        return this.siteCode;
    }
    
    public void setSiteCode(String siteCode) {
        this.siteCode = siteCode;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getRst() {
        return this.rst;
    }
    
    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public String getRuu() {
        return this.ruu;
    }
    
    public void setRuu(String ruu) {
        this.ruu = ruu;
    }

	public boolean getStatus() {
		return status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public String getManager() {
		return manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}
   
}