package db.essp.timesheet;

import java.util.Date;


/**
 * AttLeave generated by MyEclipse - Hibernate Tools
 */

public class AttLeave  implements java.io.Serializable {


    // Fields    

     private Long rid;
     private String companyId;
     private String employeeId;
     private Date leaveDate;
     private String unitCode;
     private String phaseCode;
     private Double hours;
     private Double actualHours;
     private String status;
     private Date rct;
     private Date rut;
   
    // Property accessors

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    public Date getLeaveDate() {
        return this.leaveDate;
    }
    
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    public String getUnitCode() {
        return this.unitCode;
    }
    
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }

    public String getPhaseCode() {
		return phaseCode;
	}

	public void setPhaseCode(String phaseCode) {
		this.phaseCode = phaseCode;
	}

	public Double getHours() {
        return this.hours;
    }
    
    public void setHours(Double hours) {
        this.hours = hours;
    }

    public Double getActualHours() {
        return this.actualHours;
    }
    
    public void setActualHours(Double actualHours) {
        this.actualHours = actualHours;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }
}