package db.essp.timesheet;

import java.util.Date;

/**
 * TsDailyReport generated by MyEclipse Persistence Tools
 */

public class TsDailyReport implements java.io.Serializable {

	// Fields

	private Long rid;
	private Long stepRid;
	private Long taskId;
	private String taskName;
	private Long projId;
	private String projName;
	private Long codeValueRid;
	private String codeValueName;
	private String item;
	private Date reportDate;
	private Double workTime;
	private String resourceId;
	private String rst;
	private Date rct;
	private Date rut;
	private String rcu;
	private String ruu;
	private String description;
	private Long accountRid;

	// Constructors

	public Long getAccountRid() {
		return accountRid;
	}

	public void setAccountRid(Long accountRid) {
		this.accountRid = accountRid;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	/** default constructor */
	public TsDailyReport() {
	}

	/** minimal constructor */
	public TsDailyReport(Long rid, Long projId, String projName,
			Long codeValueRid, String item, Date reportDate, Double workTime,
			String resourceId) {
		this.rid = rid;
		this.projId = projId;
		this.projName = projName;
		this.codeValueRid = codeValueRid;
		this.item = item;
		this.reportDate = reportDate;
		this.workTime = workTime;
		this.resourceId = resourceId;
	}

	/** full constructor */
	public TsDailyReport(Long rid, Long stepRid, Long taskId, String taskName,
			Long projId, String projName, Long codeValueRid, String item,
			Date reportDate, Double workTime, String resourceId, String rst,
			Date rct, Date rut, String rcu, String ruu) {
		this.rid = rid;
		this.stepRid = stepRid;
		this.taskId = taskId;
		this.taskName = taskName;
		this.projId = projId;
		this.projName = projName;
		this.codeValueRid = codeValueRid;
		this.item = item;
		this.reportDate = reportDate;
		this.workTime = workTime;
		this.resourceId = resourceId;
		this.rst = rst;
		this.rct = rct;
		this.rut = rut;
		this.rcu = rcu;
		this.ruu = ruu;
	}

	// Property accessors

	public Long getRid() {
		return this.rid;
	}

	public void setRid(Long rid) {
		this.rid = rid;
	}

	public Long getStepRid() {
		return this.stepRid;
	}

	public void setStepRid(Long stepRid) {
		this.stepRid = stepRid;
	}

	public Long getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	public Long getProjId() {
		return this.projId;
	}

	public void setProjId(Long projId) {
		this.projId = projId;
	}

	public String getProjName() {
		return this.projName;
	}

	public void setProjName(String projName) {
		this.projName = projName;
	}

	public Long getCodeValueRid() {
		return this.codeValueRid;
	}

	public void setCodeValueRid(Long codeValueRid) {
		this.codeValueRid = codeValueRid;
	}

	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	public Double getWorkTime() {
		return this.workTime;
	}

	public void setWorkTime(Double workTime) {
		this.workTime = workTime;
	}

	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	public String getRst() {
		return this.rst;
	}

	public void setRst(String rst) {
		this.rst = rst;
	}

	public Date getRct() {
		return this.rct;
	}

	public void setRct(Date rct) {
		this.rct = rct;
	}

	public Date getRut() {
		return this.rut;
	}

	public void setRut(Date rut) {
		this.rut = rut;
	}

	public String getRcu() {
		return this.rcu;
	}

	public void setRcu(String rcu) {
		this.rcu = rcu;
	}

	public String getRuu() {
		return this.ruu;
	}

	public void setRuu(String ruu) {
		this.ruu = ruu;
	}

	public String getCodeValueName() {
		return codeValueName;
	}

	public void setCodeValueName(String codeValueName) {
		this.codeValueName = codeValueName;
	}

}