package db.essp.timesheet;

import java.util.Date;

/**
 * TsException generated by MyEclipse Persistence Tools
 */

public class TsException implements java.io.Serializable {

	// Fields

	private Long rid;
	private String model;
	private String projectId;
	private String employeeId;
	private String errorMessage;
	private String status;
	private Date rct;
	private Date rut;
	private String rcu;
	private String ruu;
	private String operation;

	// Constructors

	/** default constructor */
	public TsException() {
	}

	/** minimal constructor */
	public TsException(Long rid) {
		this.rid = rid;
	}

	/** full constructor */
	public TsException(Long rid, String model, String projectId,
			String employeeId, String errorMessage, String status, Date rct,
			Date rut, String rcu, String ruu, String operation) {
		this.rid = rid;
		this.model = model;
		this.projectId = projectId;
		this.employeeId = employeeId;
		this.errorMessage = errorMessage;
		this.status = status;
		this.rct = rct;
		this.rut = rut;
		this.rcu = rcu;
		this.ruu = ruu;
		this.operation = operation;
	}

	// Property accessors

	public Long getRid() {
		return this.rid;
	}

	public void setRid(Long rid) {
		this.rid = rid;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getRct() {
		return this.rct;
	}

	public void setRct(Date rct) {
		this.rct = rct;
	}

	public Date getRut() {
		return this.rut;
	}

	public void setRut(Date rut) {
		this.rut = rut;
	}

	public String getRcu() {
		return this.rcu;
	}

	public void setRcu(String rcu) {
		this.rcu = rcu;
	}

	public String getRuu() {
		return this.ruu;
	}

	public void setRuu(String ruu) {
		this.ruu = ruu;
	}

	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

}