package db.essp.timesheet;

import java.util.Date;


/**
 * TsHumanBase generated by MyEclipse - Hibernate Tools
 */

public class TsHumanBase  implements java.io.Serializable {


    // Fields    

     private Long rid;
     private String employeeId;
     private String unitCode;
     private String englishName;
     private String chineseName;
     private String title;
     private String rank;
     private String resManagerId;
     private String resManagerName;
     private String email;
     private String site;
     private Date inDate;
     private Date outDate;
     private Date effectiveDate;
     private String attribute;
     private String isDirect;
     private Date rct;
     private Date rut;
     private String rcu;
     private String ruu;
   
    // Property accessors

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    public String getUnitCode() {
        return this.unitCode;
    }
    
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }

    public String getEnglishName() {
        return this.englishName;
    }
    
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    public String getChineseName() {
        return this.chineseName;
    }
    
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getRank() {
        return this.rank;
    }
    
    public void setRank(String rank) {
        this.rank = rank;
    }

    public String getResManagerId() {
        return this.resManagerId;
    }
    
    public void setResManagerId(String resManagerId) {
        this.resManagerId = resManagerId;
    }

    public String getResManagerName() {
        return this.resManagerName;
    }
    
    public void setResManagerName(String resManagerName) {
        this.resManagerName = resManagerName;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }

    public Date getInDate() {
        return this.inDate;
    }
    
    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    public Date getOutDate() {
        return this.outDate;
    }
    
    public void setOutDate(Date outDate) {
        this.outDate = outDate;
    }

    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    public String getAttribute() {
        return this.attribute;
    }
    
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public String getRuu() {
        return this.ruu;
    }
    
    public void setRuu(String ruu) {
        this.ruu = ruu;
    }
    
    /**
     * englishName(chineseName)
     * @return
     */
    public String getFullName() {
        return ecName2FullName(this.getEnglishName(), this.getChineseName());
    }
    
    public static String ecName2FullName(final String eName, final String cName) {
        String fullName = eName;
        if(fullName == null) {
            return cName;
        }
        if(cName != null && "".equals(cName) == false) {
            fullName += "(" + cName + ")";
        }
        return fullName;
    }

	public String getIsDirect() {
		return isDirect;
	}

	public void setIsDirect(String isDirect) {
		this.isDirect = isDirect;
	}

  
}