package db.essp.timesheet;

import java.util.Date;


/**
 * TsImportTemp generated by MyEclipse - Hibernate Tools
 */

public class TsImportTemp  implements java.io.Serializable {


    // Fields    

     private Long rid;
     private String loginId;
     private Long tsId;
     private Long acntRid;
     private Long codeValueRid;
     private Date beginDate;
     private Date endDate;
     private String acntId;
     private String workCode;
     private Double sumStandardHours;
     private Double totalHours;
     private Double foodAmount;
     private Double trafficAmount;
     private Double mondayHours;
     private Double tuesdayHours;
     private Double wednesdayHours;
     private Double thursdayHours;
     private Double fridayHours;
     private Double saturdayHours;
     private Double sundayHours;
     private String remark;
     private Boolean isLeaveType;


    // Constructors

    public Boolean getIsLeaveType() {
        return isLeaveType;
    }

    public void setIsLeaveType(Boolean isLeaveType) {
        this.isLeaveType = isLeaveType;
    }

    /** default constructor */
    public TsImportTemp() {
    }

	/** minimal constructor */
    public TsImportTemp(Long rid) {
        this.rid = rid;
    }
    
    /** full constructor */
    public TsImportTemp(Long rid, String loginId,Long acntRid,Long tsId,Long codeValueRid, Date beginDate, Date endDate, String acntId, String workCode, Double sumStandardHours, Double totalHours, Double foodAmount, Double trafficAmount, Double mondayHours, Double tuesdayHours, Double wednesdayHours, Double thursdayHours, Double fridayHours, Double saturdayHours, Double sundayHours, String remark,Boolean isLeaveType) {
        this.rid = rid;
        this.loginId = loginId;
        this.beginDate = beginDate;
        this.tsId = tsId;
        this.acntRid = acntRid;
        this.codeValueRid = codeValueRid;
        this.endDate = endDate;
        this.acntId = acntId;
        this.workCode = workCode;
        this.sumStandardHours = sumStandardHours;
        this.totalHours = totalHours;
        this.foodAmount = foodAmount;
        this.trafficAmount = trafficAmount;
        this.mondayHours = mondayHours;
        this.tuesdayHours = tuesdayHours;
        this.wednesdayHours = wednesdayHours;
        this.thursdayHours = thursdayHours;
        this.fridayHours = fridayHours;
        this.saturdayHours = saturdayHours;
        this.sundayHours = sundayHours;
        this.remark = remark;
        this.isLeaveType=isLeaveType;
    }

   
    // Property accessors

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getAcntId() {
        return this.acntId;
    }
    
    public void setAcntId(String acntId) {
        this.acntId = acntId;
    }

    public String getWorkCode() {
        return this.workCode;
    }
    
    public void setWorkCode(String workCode) {
        this.workCode = workCode;
    }

    public Double getTotalHours() {
        return this.totalHours;
    }
    
    public void setTotalHours(Double totalHours) {
        this.totalHours = totalHours;
    }

    public Double getFoodAmount() {
        return this.foodAmount;
    }
    
    public void setFoodAmount(Double foodAmount) {
        this.foodAmount = foodAmount;
    }

    public Double getTrafficAmount() {
        return this.trafficAmount;
    }
    
    public void setTrafficAmount(Double trafficAmount) {
        this.trafficAmount = trafficAmount;
    }

    public Double getMondayHours() {
        return this.mondayHours;
    }
    
    public void setMondayHours(Double mondayHours) {
        this.mondayHours = mondayHours;
    }

    public Double getTuesdayHours() {
        return this.tuesdayHours;
    }
    
    public void setTuesdayHours(Double tuesdayHours) {
        this.tuesdayHours = tuesdayHours;
    }

    public Double getWednesdayHours() {
        return this.wednesdayHours;
    }
    
    public void setWednesdayHours(Double wednesdayHours) {
        this.wednesdayHours = wednesdayHours;
    }

    public Double getThursdayHours() {
        return this.thursdayHours;
    }
    
    public void setThursdayHours(Double thursdayHours) {
        this.thursdayHours = thursdayHours;
    }

    public Double getFridayHours() {
        return this.fridayHours;
    }
    
    public void setFridayHours(Double fridayHours) {
        this.fridayHours = fridayHours;
    }

    public Double getSaturdayHours() {
        return this.saturdayHours;
    }
    
    public void setSaturdayHours(Double saturdayHours) {
        this.saturdayHours = saturdayHours;
    }

    public Double getSundayHours() {
        return this.sundayHours;
    }
    
    public void setSundayHours(Double sundayHours) {
        this.sundayHours = sundayHours;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Long getAcntRid() {
        return acntRid;
    }

    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }

    public Long getCodeValueRid() {
        return codeValueRid;
    }

    public void setCodeValueRid(Long codeValueRid) {
        this.codeValueRid = codeValueRid;
    }

    public String getLoginId() {
        return loginId;
    }

    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    public Double getSumStandardHours() {
        return sumStandardHours;
    }

    public void setSumStandardHours(Double sumStandardHours) {
        this.sumStandardHours = sumStandardHours;
    }

    public Long getTsId() {
        return tsId;
    }

    public void setTsId(Long tsId) {
        this.tsId = tsId;
    }

    public Date getBeginDate() {
        return beginDate;
    }

    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
   








}