package db.essp.timesheet;

/**
 * TsMethodTMapId generated by MyEclipse Persistence Tools
 */

public class TsMethodTMapId implements java.io.Serializable {

	// Fields

	private Long methodRid;
	private Long templateRid;

	// Constructors

	/** default constructor */
	public TsMethodTMapId() {
	}

	/** full constructor */
	public TsMethodTMapId(Long methodRid, Long templateRid) {
		this.methodRid = methodRid;
		this.templateRid = templateRid;
	}

	// Property accessors

	public Long getMethodRid() {
		return this.methodRid;
	}

	public void setMethodRid(Long methodRid) {
		this.methodRid = methodRid;
	}

	public Long getTemplateRid() {
		return this.templateRid;
	}

	public void setTemplateRid(Long templateRid) {
		this.templateRid = templateRid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TsMethodTMapId))
			return false;
		TsMethodTMapId castOther = (TsMethodTMapId) other;

		return ((this.getMethodRid() == castOther.getMethodRid()) || (this
				.getMethodRid() != null
				&& castOther.getMethodRid() != null && this.getMethodRid()
				.equals(castOther.getMethodRid())))
				&& ((this.getTemplateRid() == castOther.getTemplateRid()) || (this
						.getTemplateRid() != null
						&& castOther.getTemplateRid() != null && this
						.getTemplateRid().equals(castOther.getTemplateRid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMethodRid() == null ? 0 : this.getMethodRid().hashCode());
		result = 37
				* result
				+ (getTemplateRid() == null ? 0 : this.getTemplateRid()
						.hashCode());
		return result;
	}

}