package db.essp.timesheet;

import java.util.Date;


/**
 * TsOutworkerPrivilege generated by MyEclipse - Hibernate Tools
 */

public class TsOutworkerPrivilege  implements java.io.Serializable {


    // Fields    

     private Long rid;
     private String loginId;
     private String loginName;
     private Long acntRid;
     private String acntId;
     private String acntName;
     private String rst;
     private Date rct;
     private Date rut;
     private String rcu;
     private String ruu;


    // Constructors

    /** default constructor */
    public TsOutworkerPrivilege() {
    }

	/** minimal constructor */
    public TsOutworkerPrivilege(Long rid, String loginId, Long acntRid) {
        this.rid = rid;
        this.loginId = loginId;
        this.acntRid = acntRid;
    }
    
    /** full constructor */
    public TsOutworkerPrivilege(Long rid, String loginId, String loginName,
            Long acntRid, String acntId, String acntName,String rst,Date rct, Date rut, String rcu, String ruu) {
        this.rid = rid;
        this.loginId = loginId;
        this.loginName = loginName;
        this.acntRid = acntRid;
        this.acntId = acntId;
        this.acntName = acntName;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
        this.rcu = rcu;
        this.ruu = ruu;
    }

   
    // Property accessors

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public Long getAcntRid() {
        return this.acntRid;
    }
    
    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }

    public String getRcu() {
        return this.rcu;
    }
    
    public void setRcu(String rcu) {
        this.rcu = rcu;
    }

    public String getRuu() {
        return this.ruu;
    }
    
    public void setRuu(String ruu) {
        this.ruu = ruu;
    }

    public String getAcntId() {
        return acntId;
    }

    public void setAcntId(String acntId) {
        this.acntId = acntId;
    }

    public String getAcntName() {
        return acntName;
    }

    public void setAcntName(String acntName) {
        this.acntName = acntName;
    }

    public String getRst() {
        return rst;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }
   








}