package db.essp.timesheet;



/**
 * TsRmMaint generated by MyEclipse - Hibernate Tools
 */

public class TsRmMaint  implements java.io.Serializable {


    // Fields    

     private Long rid;
     private String loginId;
     private String rmId;


    // Constructors

    /** default constructor */
    public TsRmMaint() {
    }

	/** minimal constructor */
    public TsRmMaint(Long rid) {
        this.rid = rid;
    }
    
    /** full constructor */
    public TsRmMaint(Long rid, String loginId, String rmId) {
        this.rid = rid;
        this.loginId = loginId;
        this.rmId = rmId;
    }

   
    // Property accessors

    public Long getRid() {
        return this.rid;
    }
    
    public void setRid(Long rid) {
        this.rid = rid;
    }

    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    public String getRmId() {
        return this.rmId;
    }
    
    public void setRmId(String rmId) {
        this.rmId = rmId;
    }
   








}