package db.essp.timesheet;

import java.util.Date;

/**
 * TsStep generated by MyEclipse Persistence Tools
 */

public class TsStep implements java.io.Serializable {

	// Fields

	private Long rid;
	private Long stepTRid;
	private Long procId;
	private Long taskId;
	private Long seqNum;
	private Long projId;
	private Boolean completeFlag;
	private String procName;
	private Double procWt;
	private Double completePct;
	private String procDescr;
	private Date planStart;
	private Date planFinish;
	private Date actualStart;
	private Date actualFinish;
	private Double actualCostTime;
	private String resourceId;
	private String resourceName;
	private String category;
	private Boolean isCorp;
	private String function;
	private String isSync;
	private String rst;
	private Date rct;
	private Date rut;
	private String rcu;
	private String ruu;

	// Constructors

	/** default constructor */
	public TsStep() {
	}

	/** minimal constructor */
	public TsStep(Long rid, Long procId, Long taskId, Long seqNum, Long projId,
			Boolean completeFlag, String procName, String resourceName,
			String category, Boolean isCorp, String isSync, String rst) {
		this.rid = rid;
		this.procId = procId;
		this.taskId = taskId;
		this.seqNum = seqNum;
		this.projId = projId;
		this.completeFlag = completeFlag;
		this.procName = procName;
		this.resourceName = resourceName;
		this.category = category;
		this.isCorp = isCorp;
		this.isSync = isSync;
		this.rst = rst;
	}

	/** full constructor */
	public TsStep(Long rid, Long procId, Long taskId, Long seqNum, Long projId,
			Boolean completeFlag, String procName, Double procWt,
			Double completePct, String procDescr, Date planStart,
			Date planFinish, Date actualStart, Double actualCostTime,
			String resourceId, String resourceName, String category,
			Boolean isCorp, String function, String isSync, String rst,
			Date rct, Date rut, String rcu, String ruu) {
		this.rid = rid;
		this.procId = procId;
		this.taskId = taskId;
		this.seqNum = seqNum;
		this.projId = projId;
		this.completeFlag = completeFlag;
		this.procName = procName;
		this.procWt = procWt;
		this.completePct = completePct;
		this.procDescr = procDescr;
		this.planStart = planStart;
		this.planFinish = planFinish;
		this.actualStart = actualStart;
		this.actualCostTime = actualCostTime;
		this.resourceId = resourceId;
		this.resourceName = resourceName;
		this.category = category;
		this.isCorp = isCorp;
		this.function = function;
		this.isSync = isSync;
		this.rst = rst;
		this.rct = rct;
		this.rut = rut;
		this.rcu = rcu;
		this.ruu = ruu;
	}

	// Property accessors

	public Long getRid() {
		return this.rid;
	}

	public void setRid(Long rid) {
		this.rid = rid;
	}

	public Long getProcId() {
		return this.procId;
	}

	public void setProcId(Long procId) {
		this.procId = procId;
	}

	public Long getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

	public Long getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(Long seqNum) {
		this.seqNum = seqNum;
	}

	public Long getProjId() {
		return this.projId;
	}

	public void setProjId(Long projId) {
		this.projId = projId;
	}

	public Boolean getCompleteFlag() {
		return this.completeFlag;
	}

	public void setCompleteFlag(Boolean completeFlag) {
		this.completeFlag = completeFlag;
	}

	public String getProcName() {
		return this.procName;
	}

	public void setProcName(String procName) {
		this.procName = procName;
	}

	public Double getProcWt() {
		return this.procWt;
	}

	public void setProcWt(Double procWt) {
		this.procWt = procWt;
	}

	public Double getCompletePct() {
		return this.completePct;
	}

	public void setCompletePct(Double completePct) {
		this.completePct = completePct;
	}

	public String getProcDescr() {
		return this.procDescr;
	}

	public void setProcDescr(String procDescr) {
		this.procDescr = procDescr;
	}

	public Date getPlanStart() {
		return this.planStart;
	}

	public void setPlanStart(Date planStart) {
		this.planStart = planStart;
	}

	public Date getPlanFinish() {
		return this.planFinish;
	}

	public void setPlanFinish(Date planFinish) {
		this.planFinish = planFinish;
	}

	public Date getActualStart() {
		return this.actualStart;
	}

	public void setActualStart(Date actualStart) {
		this.actualStart = actualStart;
	}

	public Double getActualCostTime() {
		return this.actualCostTime;
	}

	public void setActualCostTime(Double actualCostTime) {
		this.actualCostTime = actualCostTime;
	}

	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Boolean getIsCorp() {
		return this.isCorp;
	}

	public void setIsCorp(Boolean isCorp) {
		this.isCorp = isCorp;
	}

	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	public String getIsSync() {
		return this.isSync;
	}

	public void setIsSync(String isSync) {
		this.isSync = isSync;
	}

	public String getRst() {
		return this.rst;
	}

	public void setRst(String rst) {
		this.rst = rst;
	}

	public Date getRct() {
		return this.rct;
	}

	public void setRct(Date rct) {
		this.rct = rct;
	}

	public Date getRut() {
		return this.rut;
	}

	public void setRut(Date rut) {
		this.rut = rut;
	}

	public String getRcu() {
		return this.rcu;
	}

	public void setRcu(String rcu) {
		this.rcu = rcu;
	}

	public String getRuu() {
		return this.ruu;
	}

	public void setRuu(String ruu) {
		this.ruu = ruu;
	}

	public Date getActualFinish() {
		return actualFinish;
	}

	public void setActualFinish(Date actualFinish) {
		this.actualFinish = actualFinish;
	}

	public Long getStepTRid() {
		return stepTRid;
	}

	public void setStepTRid(Long stepTRid) {
		this.stepTRid = stepTRid;
	}

}