package db.essp.timesheet;

import java.util.Date;

/**
 * TsStepTDetail generated by MyEclipse Persistence Tools
 */

public class TsStepTDetail implements java.io.Serializable {

	// Fields

	private Long rid;
	private Long tempRid;
	private Long seqNum;
	private String procName;
	private Double procWt;
	private String procDescr;
	private Long planStartOffset;
	private Long planFinishOffset;
	private String category;
	private String isCorp;
	private String rst;
	private Date rct;
	private Date rut;
	private String rcu;
	private String ruu;

	// Constructors

	/** default constructor */
	public TsStepTDetail() {
	}

	/** minimal constructor */
	public TsStepTDetail(Long rid, Long tempRid, Long seqNum, String procName,
			Long planStartOffset, Long planFinishOffset, String category,
			String isCorp) {
		this.rid = rid;
		this.tempRid = tempRid;
		this.seqNum = seqNum;
		this.procName = procName;
		this.planStartOffset = planStartOffset;
		this.planFinishOffset = planFinishOffset;
		this.category = category;
		this.isCorp = isCorp;
	}

	/** full constructor */
	public TsStepTDetail(Long rid, Long tempRid, Long seqNum, String procName,
			Double procWt, String procDescr, Long planStartOffset,
			Long planFinishOffset, String category, String isCorp, String rst,
			Date rct, Date rut, String rcu, String ruu) {
		this.rid = rid;
		this.tempRid = tempRid;
		this.seqNum = seqNum;
		this.procName = procName;
		this.procWt = procWt;
		this.procDescr = procDescr;
		this.planStartOffset = planStartOffset;
		this.planFinishOffset = planFinishOffset;
		this.category = category;
		this.isCorp = isCorp;
		this.rst = rst;
		this.rct = rct;
		this.rut = rut;
		this.rcu = rcu;
		this.ruu = ruu;
	}

	// Property accessors

	public Long getRid() {
		return this.rid;
	}

	public void setRid(Long rid) {
		this.rid = rid;
	}

	public Long getTempRid() {
		return this.tempRid;
	}

	public void setTempRid(Long tempRid) {
		this.tempRid = tempRid;
	}

	public Long getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(Long seqNum) {
		this.seqNum = seqNum;
	}

	public String getProcName() {
		return this.procName;
	}

	public void setProcName(String procName) {
		this.procName = procName;
	}

	public Double getProcWt() {
		return this.procWt;
	}

	public void setProcWt(Double procWt) {
		this.procWt = procWt;
	}

	public String getProcDescr() {
		return this.procDescr;
	}

	public void setProcDescr(String procDescr) {
		this.procDescr = procDescr;
	}

	public Long getPlanStartOffset() {
		return this.planStartOffset;
	}

	public void setPlanStartOffset(Long planStartOffset) {
		this.planStartOffset = planStartOffset;
	}

	public Long getPlanFinishOffset() {
		return this.planFinishOffset;
	}

	public void setPlanFinishOffset(Long planFinishOffset) {
		this.planFinishOffset = planFinishOffset;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getIsCorp() {
		return this.isCorp;
	}

	public void setIsCorp(String isCorp) {
		this.isCorp = isCorp;
	}

	public String getRst() {
		return this.rst;
	}

	public void setRst(String rst) {
		this.rst = rst;
	}

	public Date getRct() {
		return this.rct;
	}

	public void setRct(Date rct) {
		this.rct = rct;
	}

	public Date getRut() {
		return this.rut;
	}

	public void setRut(Date rut) {
		this.rut = rut;
	}

	public String getRcu() {
		return this.rcu;
	}

	public void setRcu(String rcu) {
		this.rcu = rcu;
	}

	public String getRuu() {
		return this.ruu;
	}

	public void setRuu(String ruu) {
		this.ruu = ruu;
	}

}