package db.essp.pms;

import java.util.Date;


/**
 * ActivityTest generated by MyEclipse - Hibernate Tools
 */

public class ActivityTest implements java.io.Serializable {

    private Long rid;
    private Date start;
    private Date finish;
    private Long totalTestCase;
    private Long removedDefectNum;
    private Long seq;
    private String comment;
    private String rst;
    public Date rct;
    public Date rut;
    private Long usingTestCase;
    private Long acntRid;
    private Long activityRid;
    private String testRound;

    public ActivityTest() {
    }

    public Long getAcntRid() {
        return acntRid;
    }

    public Long getActivityRid() {
        return activityRid;
    }

    public String getComment() {
        return comment;
    }

    public Date getFinish() {
        return finish;
    }

    public Long getRemovedDefectNum() {
        return removedDefectNum;
    }

    public Long getRid() {
        return rid;
    }

    public String getRst() {
        return rst;
    }

    public Long getSeq() {
        return seq;
    }

    public Date getStart() {
        return start;
    }

    public String getTestRound() {
        return testRound;
    }

    public Long getTotalTestCase() {
        return totalTestCase;
    }

    public Long getUsingTestCase() {
        return usingTestCase;
    }

    public Date getRct() {
        return rct;
    }

    public Date getRut() {
        return rut;
    }

    public void setUsingTestCase(Long usingTestCase) {
        this.usingTestCase = usingTestCase;
    }

    public void setTotalTestCase(Long totalTestCase) {
        this.totalTestCase = totalTestCase;
    }

    public void setTestRound(String testRound) {
        this.testRound = testRound;
    }

    public void setStart(Date start) {
        this.start = start;
    }

    public void setSeq(Long seq) {
        this.seq = seq;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }

    public void setRid(Long rid) {
        this.rid = rid;
    }

    public void setRemovedDefectNum(Long removedDefectNum) {
        this.removedDefectNum = removedDefectNum;
    }

    public void setFinish(Date finish) {
        this.finish = finish;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public void setActivityRid(Long activityRid) {
        this.activityRid = activityRid;
    }

    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }

    public void setRct(Date rct) {
        this.rct = rct;
    }

    public void setRut(Date rut) {
        this.rut = rut;
    }
}
