package db.essp.pms;

import java.util.Date;


/**
 * PmsActivityQuality generated by MyEclipse - Hibernate Tools
 */

public class ActivityQuality implements java.io.Serializable {


    // Fields

    public ActivityPK pk;
    public String type;
    public String production;
    public String criterion;
    public String method;
    public String remark;
    public Double planSize;
    public Double actualSize;
    public Long actualCaseNum;
    public Double actualDensity;
    public String conclusionBy;
    public String conclusion;
    public String reason;
    public String rst;
    public Date rct;
    public Date rut;
    public Long actualDefectNum;
    public Double actualDefectRate;
    private String isPass;


    // Constructors

    /** default constructor */
    public ActivityQuality() {
    }

    /** minimal constructor */
    public ActivityQuality(ActivityPK pk) {
        this.pk = pk;
    }

    /** full constructor */
    public ActivityQuality(ActivityPK pk, String type,
                           String production, String criterion, String method,
                           String remark, Double planSize, Double actualSize,
                           Long actualCaseNum, Double actualDensity,
                           String conclusionBy, String conclusion,
                           String reason, String rst, Date rct, Date rut,
                           Long actualDefectNum, Double actualDefectRate) {
        this.pk = pk;
        this.type = type;
        this.production = production;
        this.criterion = criterion;
        this.method = method;
        this.remark = remark;
        this.planSize = planSize;
        this.actualSize = actualSize;
        this.actualCaseNum = actualCaseNum;
        this.actualDensity = actualDensity;
        this.conclusionBy = conclusionBy;
        this.conclusion = conclusion;
        this.reason = reason;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
        this.actualDefectNum = actualDefectNum;
        this.actualDefectRate = actualDefectRate;
    }


    // Property accessors

    public ActivityPK getPk() {

        return pk;
    }

    public void setPk(ActivityPK pk) {

        this.pk = pk;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getProduction() {
        return this.production;
    }

    public void setProduction(String production) {
        this.production = production;
    }

    public String getCriterion() {
        return this.criterion;
    }

    public void setCriterion(String criterion) {
        this.criterion = criterion;
    }

    public String getMethod() {
        return this.method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Double getPlanSize() {
        return this.planSize;
    }

    public void setPlanSize(Double planSize) {
        this.planSize = planSize;
    }

    public Double getActualSize() {
        return this.actualSize;
    }

    public void setActualSize(Double actualSize) {
        this.actualSize = actualSize;
    }

    public Long getActualCaseNum() {
        return this.actualCaseNum;
    }

    public void setActualCaseNum(Long actualCaseNum) {
        this.actualCaseNum = actualCaseNum;
    }

    public Double getActualDensity() {
        return this.actualDensity;
    }

    public void setActualDensity(Double actualDensity) {
        this.actualDensity = actualDensity;
    }

    public String getConclusionBy() {
        return this.conclusionBy;
    }

    public void setConclusionBy(String conclusionBy) {
        this.conclusionBy = conclusionBy;
    }

    public String getConclusion() {
        return this.conclusion;
    }

    public void setConclusion(String conclusion) {
        this.conclusion = conclusion;
    }

    public String getReason() {
        return this.reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getRst() {
        return this.rst;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }

    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }

    public void setRut(Date rut) {
        this.rut = rut;
    }

    public Long getActualDefectNum() {
        return this.actualDefectNum;
    }

    public void setActualDefectNum(Long actualDefectNum) {
        this.actualDefectNum = actualDefectNum;
    }

    public Double getActualDefectRate() {
        return this.actualDefectRate;
    }

    public String getIsPass() {
        return isPass;
    }

    public void setActualDefectRate(Double actualDefectRate) {
        this.actualDefectRate = actualDefectRate;
    }

    public void setIsPass(String isPass) {
        this.isPass = isPass;
    }


}
