package db.essp.pms;

import java.util.Date;


/**
 * ActivityTestStat generated by MyEclipse - Hibernate Tools
 */

public class ActivityTestStat implements java.io.Serializable {


    // Fields
    private Long rid;
    private Long testRid;
    private String injectedPhase;
    private Long defectNum;
    private String rst;
    public Date rct;
    public Date rut;
    private Long acntRid;

    public ActivityTestStat() {
    }

    public Long getAcntRid() {
        return acntRid;
    }

    public Long getDefactNum() {
        return defectNum;
    }

    public String getInjectedPhase() {
        return injectedPhase;
    }

    public Long getRid() {
        return rid;
    }

    public String getRst() {
        return rst;
    }

    public Long getTestRid() {
        return testRid;
    }

    public Long getDefectNum() {
        return defectNum;
    }

    public Date getRct() {
        return rct;
    }

    public Date getRut() {
        return rut;
    }

    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }



    public void setInjectedPhase(String injectedPhase) {
        this.injectedPhase = injectedPhase;
    }

    public void setRid(Long rid) {
        this.rid = rid;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }

    public void setTestRid(Long testRid) {
        this.testRid = testRid;
    }

    public void setDefectNum(Long defectNum) {
        this.defectNum = defectNum;
    }

    public void setRut(Date rut) {
        this.rut = rut;
    }

    public void setRct(Date rct) {
        this.rct = rct;
    }


}
