package db.essp.pms;



/**
 * PmsActivityGuidelineId generated by MyEclipse - Hibernate Tools
 */

public class PmsActivityGuidelineId  implements java.io.Serializable {


    // Fields    

     private Long acntRid;
     private Long actRid;


    // Constructors

    /** default constructor */
    public PmsActivityGuidelineId() {
    }

    

   
    // Property accessors

    public Long getAcntRid() {
        return this.acntRid;
    }
    
    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }

    public Long getActRid() {
        return this.actRid;
    }
    
    public void setActRid(Long actRid) {
        this.actRid = actRid;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PmsActivityGuidelineId) ) return false;
		 PmsActivityGuidelineId castOther = ( PmsActivityGuidelineId ) other; 
         
		 return ( (this.getAcntRid()==castOther.getAcntRid()) || ( this.getAcntRid()!=null && castOther.getAcntRid()!=null && this.getAcntRid().equals(castOther.getAcntRid()) ) )
 && ( (this.getActRid()==castOther.getActRid()) || ( this.getActRid()!=null && castOther.getActRid()!=null && this.getActRid().equals(castOther.getActRid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAcntRid() == null ? 0 : this.getAcntRid().hashCode() );
         result = 37 * result + ( getActRid() == null ? 0 : this.getActRid().hashCode() );
         return result;
   }   





}