package db.essp.pms;

import java.util.Date;


/**
 * PmsPcbItem generated by MyEclipse - Hibernate Tools
 */

public class PmsPcbItem  implements java.io.Serializable {


    // Fields

     private PmsPcbItemPK PK;
     private String name;
     private String type;
     private String remark;
     private String rst;
     private Date rct;
     private Date rut;
    private Long seq;


    // Constructors

    /** default constructor */
    public PmsPcbItem() {
    }

	/** minimal constructor */
    public PmsPcbItem(PmsPcbItemPK PK, String name, String type) {
        this.PK = PK;
        this.name = name;
        this.type = type;
    }

    /** full constructor */
    public PmsPcbItem(PmsPcbItemPK PK, String name, String type, String remark, String rst, Date rct, Date rut) {
        this.PK = PK;
        this.name = name;
        this.type = type;
        this.remark = remark;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
    }


    // Property accessors

    public PmsPcbItemPK getPK() {

        return PK;
    }

    public void setPK(PmsPcbItemPK PK) {

        this.PK = PK;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getRst() {
        return this.rst;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }

    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }

    public Long getSeq() {
        return seq;
    }

    public void setRut(Date rut) {
        this.rut = rut;
    }

    public void setSeq(Long seq) {
        this.seq = seq;
    }


}
