package db.essp.pms;

import java.util.Date;


/**
 * PmsPcbParameter generated by MyEclipse - Hibernate Tools
 */

public class PmsPcbParameter  implements java.io.Serializable {


    // Fields

     private PmsPcbParameterPK PK;
     private Long itemRid;
     private String name;
     private String unit;
     private Double ucl;
     private Double mean;
     private Double lcl;
     private Double plan;
     private String remark;
     private Double actual;
     private String rst;
     private Date rct;
     private Date rut;
     private String id;
    private Long seq;


    // Constructors

    /** default constructor */
    public PmsPcbParameter() {
    }

	/** minimal constructor */
    public PmsPcbParameter(PmsPcbParameterPK PK, Long itemRid, String name, String id) {
        this.PK = PK;
        this.itemRid = itemRid;
        this.name = name;
        this.id = id;
    }

    /** full constructor */
    public PmsPcbParameter(PmsPcbParameterPK PK, Long itemRid, String name, String unit, Double ucl, Double mean, Double lcl, Double plan, String remark, Double actual, String rst, Date rct, Date rut, String id) {
        this.PK = PK;
        this.itemRid = itemRid;
        this.name = name;
        this.unit = unit;
        this.ucl = ucl;
        this.mean = mean;
        this.lcl = lcl;
        this.plan = plan;
        this.remark = remark;
        this.actual = actual;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
        this.id = id;
    }


    // Property accessors

    public PmsPcbParameterPK getPK() {

        return PK;
    }

    public void setPK(PmsPcbParameterPK PK) {

        this.PK = PK;
    }

    public Long getItemRid() {
        return this.itemRid;
    }

    public void setItemRid(Long itemRid) {
        this.itemRid = itemRid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public Double getUcl() {
        return this.ucl;
    }

    public void setUcl(Double ucl) {
        this.ucl = ucl;
    }

    public Double getMean() {
        return this.mean;
    }

    public void setMean(Double mean) {
        this.mean = mean;
    }

    public Double getLcl() {
        return this.lcl;
    }

    public void setLcl(Double lcl) {
        this.lcl = lcl;
    }

    public Double getPlan() {
        return this.plan;
    }

    public void setPlan(Double plan) {
        this.plan = plan;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Double getActual() {
        return this.actual;
    }

    public void setActual(Double actual) {
        this.actual = actual;
    }

    public String getRst() {
        return this.rst;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }

    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }

    public void setRut(Date rut) {
        this.rut = rut;
    }

    public String getId() {
        return this.id;
    }

    public Long getSeq() {
        return seq;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setSeq(Long seq) {
        this.seq = seq;
    }


}
