package db.essp.pms;

import java.util.Date;


/**
 * PmsQaCheckPoint generated by MyEclipse - Hibernate Tools
 */

public class PmsQaCheckPoint  implements java.io.Serializable {


    // Fields

     private PmsQaCheckPointPK PK;
     private Long belongRid;
     private String belongTo;
     private String code;
     private String name;
     private String method;
    private String rst;
     private Date rct;
     private Date rut;
    private Long seq;
    private String remark;


    // Constructors

    /** default constructor */
    public PmsQaCheckPoint() {
    }

	/** minimal constructor */
    public PmsQaCheckPoint(PmsQaCheckPointPK PK, Long belongRid, String belongTo, String code) {
        this.PK = PK;
        this.belongRid = belongRid;
        this.belongTo = belongTo;
        this.code = code;
    }

    /** full constructor */
    public PmsQaCheckPoint(PmsQaCheckPointPK PK, Long belongRid, String belongTo, String name, String method, String rst, Date rct, Date rut) {
        this.PK = PK;
        this.belongRid = belongRid;
        this.belongTo = belongTo;
        this.code = code;
        this.name = name;
        this.method = method;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
    }


    // Property accessors

    public PmsQaCheckPointPK getPK() {

        return PK;
    }

    public void setPK(PmsQaCheckPointPK PK) {

        this.PK = PK;
    }

    public Long getBelongRid() {
        return this.belongRid;
    }

    public void setBelongRid(Long belongRid) {
        this.belongRid = belongRid;
    }

    public String getBelongTo() {
        return this.belongTo;
    }

    public void setBelongTo(String belongTo) {
        this.belongTo = belongTo;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMethod() {
        return this.method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getRst() {
        return this.rst;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }

    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }

    public Long getSeq() {
        return seq;
    }

    public String getRemark() {
        return remark;
    }

    public void setRut(Date rut) {
        this.rut = rut;
    }

    public void setSeq(Long seq) {
        this.seq = seq;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }


}
