package db.essp.pms;



/**
 * PmsQaCheckPointPK generated by MyEclipse - Hibernate Tools
 */

public class PmsQaCheckPointPK  implements java.io.Serializable {


    // Fields

     private Long rid;
     private Long acntRid;


    // Constructors

    /** default constructor */
    public PmsQaCheckPointPK() {
    }




    // Property accessors

    public Long getRid() {
        return this.rid;
    }

    public void setRid(Long rid) {
        this.rid = rid;
    }

    public Long getAcntRid() {
        return this.acntRid;
    }

    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }




   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PmsQaCheckPointPK) ) return false;
		 PmsQaCheckPointPK castOther = ( PmsQaCheckPointPK ) other;

		 return ( (this.getRid()==castOther.getRid()) || ( this.getRid()!=null && castOther.getRid()!=null && this.getRid().equals(castOther.getRid()) ) )
 && ( (this.getAcntRid()==castOther.getAcntRid()) || ( this.getAcntRid()!=null && castOther.getAcntRid()!=null && this.getAcntRid().equals(castOther.getAcntRid()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getRid() == null ? 0 : this.getRid().hashCode() );
         result = 37 * result + ( getAcntRid() == null ? 0 : this.getAcntRid().hashCode() );
         return result;
   }





}
