package db.essp.pms;

import java.util.Date;


/**
 * PmsStatusReportIssue generated by MyEclipse - Hibernate Tools
 */

public class PmsStatusReportIssue implements java.io.Serializable {


    // Fields

    private Long rid;
    private Long acntRid;
    private Date startdate;
    private Date finishdate;
    private String type;
    private Long addcount;
    private Long closecount;
    private Long handlecount;
    private Long abnomalcount;
    private Long totalcount;
    private String rst;
    private Date rct;
    private Date rut;


    // Constructors

    /** default constructor */
    public PmsStatusReportIssue() {
    }

    /** minimal constructor */
    public PmsStatusReportIssue(Long rid) {
        this.rid = rid;
    }

    /** full constructor */
    public PmsStatusReportIssue(Long rid, Long acntRid, Date startdate,
                                Date finishdate, String type, Long addcount,
                                Long closecount, Long handlecount,
                                Long abnomalcount, Long totalcount, String rst,
                                Date rct, Date rut) {
        this.rid = rid;
        this.acntRid = acntRid;
        this.startdate = startdate;
        this.finishdate = finishdate;
        this.type = type;
        this.addcount = addcount;
        this.closecount = closecount;
        this.handlecount = handlecount;
        this.abnomalcount = abnomalcount;
        this.totalcount = totalcount;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
    }


    // Property accessors

    public Long getRid() {
        return this.rid;
    }

    public void setRid(Long rid) {
        this.rid = rid;
    }

    public Long getAcntRid() {
        return this.acntRid;
    }

    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }

    public Date getFinishdate() {
        return this.finishdate;
    }

    public void setFinishdate(Date finishdate) {
        this.finishdate = finishdate;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Long getAddcount() {
        if(addcount == null)
            return new Long(0);
        return this.addcount;
    }

    public void setAddcount(Long addcount) {
        this.addcount = addcount;
    }

    public Long getClosecount() {
        if(closecount == null)
            return new Long(0);
        return this.closecount;
    }

    public void setClosecount(Long closecount) {
        this.closecount = closecount;
    }

    public Long getHandlecount() {
        if(handlecount == null)
            return new Long(0);
        return handlecount;
    }

    public void setHandlecount(Long handlecount) {

        this.handlecount = handlecount;
    }

    public Long getAbnomalcount() {
        if(abnomalcount == null)
            return new Long(0);
        return this.abnomalcount;
    }

    public void setAbnomalcount(Long abnomalcount) {
        this.abnomalcount = abnomalcount;
    }

    public Long getTotalcount() {
        if(totalcount == null)
            return new Long(0);
        return this.totalcount;
    }

    public void setTotalcount(Long totalcount) {
        this.totalcount = totalcount;
    }

    public String getRst() {
        return this.rst;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }

    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }

    public Date getStartdate() {
        return startdate;
    }

    public void setRut(Date rut) {
        this.rut = rut;
    }

    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }


}
