package db.essp.pms;

import java.util.Date;


/**
 * PmsStatusReportHistory generated by MyEclipse - Hibernate Tools
 */

public class PmsStatusReportHistory implements java.io.Serializable {


    // Fields

    private Long rid;
    private Long acntRid;
    private Date startdate;
    private Date finishdate;
    private String manager;
    private Double completerate;
    private Double budget;
    private Double laborcostperweek;
    private Long wpcount;
    private Long completeplancount;
    private Long completeactualcount;
    private Long totalplancount;
    private Long totalactualcount;
    private Double pv;
    private Double ev;
    private Double ac;
    private String rst;
    private Date rct;
    private Date rut;


    // Constructors

    /** default constructor */
    public PmsStatusReportHistory() {
    }

    /** minimal constructor */
    public PmsStatusReportHistory(Long rid) {
        this.rid = rid;
    }

    /** full constructor */
    public PmsStatusReportHistory(Long rid, Long acntRid, Date startdate,
                                  Date finishdate, String manager,
                                  Double completerate, Double budget,
                                  Double laborcostperweek, Long wpcount,
                                  Long completeplancount,
                                  Long completeactualcount,
                                  Long totalplancount, Long totalactualcount,
                                  Double pv, Double ev, Double ac, String rst,
                                  Date rct, Date rut) {
        this.rid = rid;
        this.acntRid = acntRid;
        this.startdate = startdate;
        this.finishdate = finishdate;
        this.manager = manager;
        this.completerate = completerate;
        this.budget = budget;
        this.laborcostperweek = laborcostperweek;
        this.wpcount = wpcount;
        this.completeplancount = completeplancount;
        this.completeactualcount = completeactualcount;
        this.totalplancount = totalplancount;
        this.totalactualcount = totalactualcount;
        this.pv = pv;
        this.ev = ev;
        this.ac = ac;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
    }


    // Property accessors

    public Long getRid() {
        return this.rid;
    }

    public void setRid(Long rid) {
        this.rid = rid;
    }

    public Long getAcntRid() {
        return this.acntRid;
    }

    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }

    public Date getFinishdate() {
        return this.finishdate;
    }

    public void setFinishdate(Date finishdate) {
        this.finishdate = finishdate;
    }

    public String getManager() {
        return this.manager;
    }

    public void setManager(String manager) {
        this.manager = manager;
    }

    public Double getCompleterate() {
        return this.completerate;
    }

    public void setCompleterate(Double completerate) {
        this.completerate = completerate;
    }

    public Double getBudget() {
        return this.budget;
    }

    public void setBudget(Double budget) {
        this.budget = budget;
    }

    public Double getLaborcostperweek() {
        return this.laborcostperweek;
    }

    public void setLaborcostperweek(Double laborcostperweek) {
        this.laborcostperweek = laborcostperweek;
    }

    public Long getWpcount() {
        return this.wpcount;
    }

    public void setWpcount(Long wpcount) {
        this.wpcount = wpcount;
    }

    public Long getCompleteplancount() {
        return this.completeplancount;
    }

    public void setCompleteplancount(Long completeplancount) {
        this.completeplancount = completeplancount;
    }

    public Long getCompleteactualcount() {
        return this.completeactualcount;
    }

    public void setCompleteactualcount(Long completeactualcount) {
        this.completeactualcount = completeactualcount;
    }

    public Long getTotalplancount() {
        return this.totalplancount;
    }

    public void setTotalplancount(Long totalplancount) {
        this.totalplancount = totalplancount;
    }

    public Long getTotalactualcount() {
        return this.totalactualcount;
    }

    public void setTotalactualcount(Long totalactualcount) {
        this.totalactualcount = totalactualcount;
    }

    public Double getPv() {
        return this.pv;
    }

    public void setPv(Double pv) {
        this.pv = pv;
    }

    public Double getEv() {
        return this.ev;
    }

    public void setEv(Double ev) {
        this.ev = ev;
    }

    public Double getAc() {
        return this.ac;
    }

    public void setAc(Double ac) {
        this.ac = ac;
    }

    public String getRst() {
        return this.rst;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }

    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }

    public Date getStartdate() {
        return startdate;
    }

    public void setRut(Date rut) {
        this.rut = rut;
    }

    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }


}
