package db.essp.pms;

import java.util.Date;


/**
 * PmsWbsGuideline generated by MyEclipse - Hibernate Tools
 */

public class PmsWbsGuideline  implements java.io.Serializable {


    // Fields    

     private PmsWbsGuidelineId id;
     private Long refAcntRid;
     private Long refWbsRid;
     private String description;
     private String rst;
     private Date rct;
     private Date rut;


    // Constructors

    /** default constructor */
    public PmsWbsGuideline() {
    }

	/** minimal constructor */
    public PmsWbsGuideline(PmsWbsGuidelineId id, Long refAcntRid, Long refWbsRid) {
        this.id = id;
        this.refAcntRid = refAcntRid;
        this.refWbsRid = refWbsRid;
    }
    
    /** full constructor */
    public PmsWbsGuideline(PmsWbsGuidelineId id, Long refAcntRid, Long refWbsRid, String description, String rst, Date rct, Date rut) {
        this.id = id;
        this.refAcntRid = refAcntRid;
        this.refWbsRid = refWbsRid;
        this.description = description;
        this.rst = rst;
        this.rct = rct;
        this.rut = rut;
    }

   
    // Property accessors

    public PmsWbsGuidelineId getId() {
        return this.id;
    }
    
    public void setId(PmsWbsGuidelineId id) {
        this.id = id;
    }

    public Long getRefAcntRid() {
        return this.refAcntRid;
    }
    
    public void setRefAcntRid(Long refAcntRid) {
        this.refAcntRid = refAcntRid;
    }

    public Long getRefWbsRid() {
        return this.refWbsRid;
    }
    
    public void setRefWbsRid(Long refWbsRid) {
        this.refWbsRid = refWbsRid;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getRst() {
        return this.rst;
    }
    
    public void setRst(String rst) {
        this.rst = rst;
    }

    public Date getRct() {
        return this.rct;
    }
    
    public void setRct(Date rct) {
        this.rct = rct;
    }

    public Date getRut() {
        return this.rut;
    }
    
    public void setRut(Date rut) {
        this.rut = rut;
    }
   








}