package db.essp.pms;



/**
 * PmsWbsGuidelineId generated by MyEclipse - Hibernate Tools
 */

public class PmsWbsGuidelineId  implements java.io.Serializable {


    // Fields

     private Long acntRid;
     private Long wbsRid;


    // Constructors

    /** default constructor */
    public PmsWbsGuidelineId() {
    }




    // Property accessors

    public Long getAcntRid() {
        return this.acntRid;
    }

    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }

    public Long getWbsRid() {
        return this.wbsRid;
    }

    public void setWbsRid(Long wbsRid) {
        this.wbsRid = wbsRid;
    }




   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PmsWbsGuidelineId) ) return false;
		 PmsWbsGuidelineId castOther = ( PmsWbsGuidelineId ) other;

		 return ( (this.getAcntRid()==castOther.getAcntRid()) || ( this.getAcntRid()!=null && castOther.getAcntRid()!=null && this.getAcntRid().equals(castOther.getAcntRid()) ) )
 && ( (this.getWbsRid()==castOther.getWbsRid()) || ( this.getWbsRid()!=null && castOther.getWbsRid()!=null && this.getWbsRid().equals(castOther.getWbsRid()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getAcntRid() == null ? 0 : this.getAcntRid().hashCode() );
         result = 37 * result + ( getWbsRid() == null ? 0 : this.getWbsRid().hashCode() );
         return result;
   }


   public String toString(){
       return super.toString() + "##acntRid["+acntRid+"]wbsRid["+wbsRid+"]";
   }


}
