package db.essp.pms;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * QualityGoal generated by MyEclipse - Hibernate Tools
 */

public class QualityGoal  implements java.io.Serializable {
     private Long rid;
     private Long acntRid ;
     private String production;
     private Long actualSize;
     private Long actualDefect;
     private Boolean isSumSize;
     private Boolean isSumDefect;
     private Long seq;
     private String rst;
     private Date rct;
     private Date rut;
     private String description;
     private Set releaseRecords = new HashSet(0);


    public Long getAcntRid() {
        return acntRid;
    }

    public Long getActualDefect() {
        return actualDefect;
    }

    public Long getActualSize() {
        return actualSize;
    }

    public String getDescription() {
        return description;
    }

    public Boolean getIsSumDefect() {
        return isSumDefect;
    }

    public Boolean getIsSumSize() {
        return isSumSize;
    }

    public String getProduction() {
        return production;
    }

    public Date getRct() {
        return rct;
    }

    public Set getReleaseRecords() {
        return releaseRecords;
    }

    public Long getRid() {
        return rid;
    }

    public String getRst() {
        return rst;
    }

    public Date getRut() {
        return rut;
    }

    public Long getSeq() {
        return seq;
    }

    public void setAcntRid(Long acntRid) {
        this.acntRid = acntRid;
    }

    public void setActualDefect(Long actualDefect) {
        this.actualDefect = actualDefect;
    }

    public void setActualSize(Long actualSize) {
        this.actualSize = actualSize;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setIsSumDefect(Boolean isSumDefect) {
        this.isSumDefect = isSumDefect;
    }

    public void setIsSumSize(Boolean isSumSize) {
        this.isSumSize = isSumSize;
    }

    public void setProduction(String production) {
        this.production = production;
    }

    public void setRct(Date rct) {
        this.rct = rct;
    }

    public void setReleaseRecords(Set releaseRecords) {
        this.releaseRecords = releaseRecords;
    }

    public void setRid(Long rid) {
        this.rid = rid;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }

    public void setRut(Date rut) {
        this.rut = rut;
    }

    public void setSeq(Long seq) {
        this.seq = seq;
    }
}
