package db.essp.pms;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * ReleaseRecord generated by MyEclipse - Hibernate Tools
 */

public class ReleaseRecord  implements java.io.Serializable {


    // Fields

     private Long rid;
     private Long goalRid;
     private String version;
     private Date releaseDate;
     private String description;
     private Date statDate;
     private Long size;
     private Long problems;
     private Long defects;
     private String rst;
     private Date rct;
     private Date rut;
      private Set QualityGoal = new HashSet(0);


    // Constructors

    /** default constructor */
    public ReleaseRecord() {
    }

    public Long getDefects() {
        return defects;
    }

    public String getDescription() {
        return description;
    }

    public Long getGoalRid() {
        return goalRid;
    }

    public Long getProblems() {
        return problems;
    }

    public Date getRct() {
        return rct;
    }

    public Date getReleaseDate() {
        return releaseDate;
    }

    public Long getRid() {
        return rid;
    }

    public String getRst() {
        return rst;
    }

    public Date getRut() {
        return rut;
    }

    public Long getSize() {
        return size;
    }

    public Date getStatDate() {
        return statDate;
    }

    public String getVersion() {
        return version;
    }

    public Set getQualityGoal() {
        return QualityGoal;
    }

    public void setDefects(Long defects) {
        this.defects = defects;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setGoalRid(Long goalRid) {
        this.goalRid = goalRid;
    }

    public void setProblems(Long problems) {
        this.problems = problems;
    }

    public void setRct(Date rct) {
        this.rct = rct;
    }

    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    public void setRid(Long rid) {
        this.rid = rid;
    }

    public void setRst(String rst) {
        this.rst = rst;
    }

    public void setRut(Date rut) {
        this.rut = rut;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public void setStatDate(Date statDate) {
        this.statDate = statDate;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public void setQualityGoal(Set QualityGoal) {
        this.QualityGoal = QualityGoal;
    }

    /** minimal constructor */


}
